// Ported from tsc/internal/core/languagevariant_stringer_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763
//
// Code generated by "stringer -type=LanguageVariant -output=languagevariant_stringer_generated.go"; DO NOT EDIT.
// PORT: Go's stringer string-slicing tables are replaced by a Display impl
// with identical strings.

use std::fmt;

use crate::languagevariant::LanguageVariant;

impl fmt::Display for LanguageVariant {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LanguageVariant::Standard => f.write_str("LanguageVariantStandard"),
            LanguageVariant::JSX => f.write_str("LanguageVariantJSX"),
        }
    }
}
