// Code generated by "stringer -type=LanguageVariant -output=languagevariant_stringer_generated.go"; DO NOT EDIT.
// PORT: generated Rust checked in; rust/tools/gen-options is TODO(gen).
// Ported from tsc/internal/core/languagevariant_stringer_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763

use crate::languagevariant::LanguageVariant;
use std::fmt;

const LANGUAGE_VARIANT_NAME: &str = "LanguageVariantStandardLanguageVariantJSX";

const LANGUAGE_VARIANT_INDEX: [u8; 3] = [0, 23, 41];

impl fmt::Display for LanguageVariant {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // PORT: Rust enums cannot hold out-of-range ordinals, so the
        // `LanguageVariant(-N)` fallback from the Go stringer is unreachable.
        let i = *self as usize;
        f.write_str(
            &LANGUAGE_VARIANT_NAME
                [LANGUAGE_VARIANT_INDEX[i] as usize..LANGUAGE_VARIANT_INDEX[i + 1] as usize],
        )
    }
}
