// Code generated by "stringer -type=ModuleKind -trimprefix=ModuleKind -output=modulekind_stringer_generated.go"; DO NOT EDIT.
// PORT: generated Rust checked in; rust/tools/gen-options is TODO(gen).
// Ported from tsc/internal/core/modulekind_stringer_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763

use crate::options_generated::ModuleKind;
use std::fmt;

const MODULE_KIND_NAME_0: &str = "NoneCommonJSAMDUMDSystemES2015ES2020ES2022";
const MODULE_KIND_NAME_1: &str = "ESNextNode16Node18Node20";
const MODULE_KIND_NAME_2: &str = "NodeNextPreserve";

const MODULE_KIND_INDEX_0: [u8; 9] = [0, 4, 12, 15, 18, 24, 30, 36, 42];
const MODULE_KIND_INDEX_1: [u8; 5] = [0, 6, 12, 18, 24];
const MODULE_KIND_INDEX_2: [u8; 3] = [0, 8, 16];

impl fmt::Display for ModuleKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // PORT: Rust enums cannot hold out-of-range ordinals, so the
        // `ModuleKind(N)` fallback from the Go stringer is unreachable.
        let i = *self as i32;
        if (0..=7).contains(&i) {
            let i = i as usize;
            return f.write_str(
                &MODULE_KIND_NAME_0
                    [MODULE_KIND_INDEX_0[i] as usize..MODULE_KIND_INDEX_0[i + 1] as usize],
            );
        }
        if (99..=102).contains(&i) {
            let i = (i - 99) as usize;
            return f.write_str(
                &MODULE_KIND_NAME_1
                    [MODULE_KIND_INDEX_1[i] as usize..MODULE_KIND_INDEX_1[i + 1] as usize],
            );
        }
        let i = (i - 199) as usize;
        f.write_str(
            &MODULE_KIND_NAME_2
                [MODULE_KIND_INDEX_2[i] as usize..MODULE_KIND_INDEX_2[i + 1] as usize],
        )
    }
}
