// Code generated by tools/scripts/tsc/generate-options.ts. DO NOT EDIT.
// PORT: generated Rust checked in; rust/tools/gen-options is TODO(gen).
// Ported from tsc/internal/core/options_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763
//
//go:generate npx hereby generate:compileroptions
//
// PORT: Go's `json:"...,omitzero"` tags become
// `#[serde(skip_serializing_if = "...")]` plus a container-level
// `#[serde(default)]`. Go's nil-able `[]string` / `*int` / `*OrderedMap`
// fields become `Option<_>` so that `Equals` can preserve the nil-vs-empty
// distinction.

use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::sync::LazyLock;
use tsc_collections::OrderedMap;
use tsc_tspath as tspath;

use crate::tristate::Tristate;

fn is_default<T: Default + PartialEq>(v: &T) -> bool {
    *v == T::default()
}

// Serde helpers for the tspath string-wrapper types, which are foreign types
// that cannot implement serde traits here (orphan rule). Go marshals them as
// plain strings without normalization.
pub(crate) mod rooted_path_serde {
    use super::*;

    pub fn serialize<S: Serializer>(p: &tspath::RootedPath, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(p.as_string())
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<tspath::RootedPath, D::Error> {
        Ok(tspath::RootedPath::from(String::deserialize(d)?))
    }
}

pub(crate) mod rooted_file_path_serde {
    use super::*;

    pub fn serialize<S: Serializer>(p: &tspath::RootedFilePath, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(p.as_string())
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(
        d: D,
    ) -> Result<tspath::RootedFilePath, D::Error> {
        Ok(tspath::RootedFilePath::from(String::deserialize(d)?))
    }
}

pub(crate) mod rooted_directory_path_serde {
    use super::*;

    pub fn serialize<S: Serializer>(
        p: &tspath::RootedDirectoryPath,
        s: S,
    ) -> Result<S::Ok, S::Error> {
        s.serialize_str(p.as_string())
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(
        d: D,
    ) -> Result<tspath::RootedDirectoryPath, D::Error> {
        Ok(tspath::RootedDirectoryPath::from(String::deserialize(d)?))
    }
}

mod rooted_directory_path_vec_serde {
    use super::*;

    pub fn serialize<S: Serializer>(
        v: &Option<Vec<tspath::RootedDirectoryPath>>,
        s: S,
    ) -> Result<S::Ok, S::Error> {
        match v {
            Some(v) => s.collect_seq(v.iter().map(|p| p.as_string())),
            None => s.serialize_none(),
        }
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(
        d: D,
    ) -> Result<Option<Vec<tspath::RootedDirectoryPath>>, D::Error> {
        Ok(Option::<Vec<String>>::deserialize(d)?.map(|v| {
            v.into_iter()
                .map(tspath::RootedDirectoryPath::from)
                .collect()
        }))
    }
}

#[derive(Clone, Default, PartialEq, Debug, Serialize, Deserialize)]
#[serde(default)]
pub struct PluginImport {
    #[serde(rename = "name")]
    pub name: String,
}

// CompilerOptions contains the compiler options exposed by the API.
//
// PORT: Go's `_ noCopy` marker is unneeded: Rust never copies structs
// implicitly.
#[derive(Clone, Default, Debug, Serialize, Deserialize)]
#[serde(default)]
pub struct CompilerOptions {
    #[serde(rename = "allowJs", skip_serializing_if = "Tristate::is_unknown")]
    pub allow_js: Tristate,
    #[serde(
        rename = "allowArbitraryExtensions",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub allow_arbitrary_extensions: Tristate,
    #[serde(
        rename = "allowImportingTsExtensions",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub allow_importing_ts_extensions: Tristate,
    #[serde(
        rename = "allowNonTsExtensions",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub allow_non_ts_extensions: Tristate,
    #[serde(
        rename = "allowUmdGlobalAccess",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub allow_umd_global_access: Tristate,
    #[serde(
        rename = "allowUnreachableCode",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub allow_unreachable_code: Tristate,
    #[serde(
        rename = "allowUnusedLabels",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub allow_unused_labels: Tristate,
    #[serde(
        rename = "assumeChangesOnlyAffectDirectDependencies",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub assume_changes_only_affect_direct_dependencies: Tristate,
    #[serde(rename = "checkJs", skip_serializing_if = "Tristate::is_unknown")]
    pub check_js: Tristate,
    #[serde(rename = "customConditions", skip_serializing_if = "Option::is_none")]
    pub custom_conditions: Option<Vec<String>>,
    #[serde(rename = "composite", skip_serializing_if = "Tristate::is_unknown")]
    pub composite: Tristate,
    #[serde(
        rename = "emitDeclarationOnly",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub emit_declaration_only: Tristate,
    #[serde(rename = "emitBOM", skip_serializing_if = "Tristate::is_unknown")]
    pub emit_bom: Tristate,
    #[serde(
        rename = "emitDecoratorMetadata",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub emit_decorator_metadata: Tristate,
    #[serde(rename = "declaration", skip_serializing_if = "Tristate::is_unknown")]
    pub declaration: Tristate,
    #[serde(
        rename = "declarationDir",
        skip_serializing_if = "str::is_empty",
        with = "rooted_directory_path_serde"
    )]
    pub declaration_dir: tspath::RootedDirectoryPath,
    #[serde(
        rename = "declarationMap",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub declaration_map: Tristate,
    #[serde(
        rename = "deduplicatePackages",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub deduplicate_packages: Tristate,
    #[serde(
        rename = "disableSizeLimit",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub disable_size_limit: Tristate,
    #[serde(
        rename = "disableSourceOfProjectReferenceRedirect",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub disable_source_of_project_reference_redirect: Tristate,
    #[serde(
        rename = "disableSolutionSearching",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub disable_solution_searching: Tristate,
    #[serde(
        rename = "disableReferencedProjectLoad",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub disable_referenced_project_load: Tristate,
    #[serde(
        rename = "erasableSyntaxOnly",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub erasable_syntax_only: Tristate,
    #[serde(
        rename = "exactOptionalPropertyTypes",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub exact_optional_property_types: Tristate,
    #[serde(
        rename = "experimentalDecorators",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub experimental_decorators: Tristate,
    #[serde(
        rename = "forceConsistentCasingInFileNames",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub force_consistent_casing_in_file_names: Tristate,
    #[serde(
        rename = "isolatedModules",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub isolated_modules: Tristate,
    #[serde(
        rename = "isolatedDeclarations",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub isolated_declarations: Tristate,
    #[serde(rename = "ignoreConfig", skip_serializing_if = "Tristate::is_unknown")]
    pub ignore_config: Tristate,
    #[serde(
        rename = "ignoreDeprecations",
        skip_serializing_if = "String::is_empty"
    )]
    pub ignore_deprecations: String,
    #[serde(rename = "importHelpers", skip_serializing_if = "Tristate::is_unknown")]
    pub import_helpers: Tristate,
    #[serde(
        rename = "inlineSourceMap",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub inline_source_map: Tristate,
    #[serde(rename = "inlineSources", skip_serializing_if = "Tristate::is_unknown")]
    pub inline_sources: Tristate,
    #[serde(rename = "init", skip_serializing_if = "Tristate::is_unknown")]
    pub init: Tristate,
    #[serde(rename = "incremental", skip_serializing_if = "Tristate::is_unknown")]
    pub incremental: Tristate,
    #[serde(rename = "jsx", skip_serializing_if = "is_default")]
    pub jsx: JsxEmit,
    #[serde(rename = "jsxFactory", skip_serializing_if = "String::is_empty")]
    pub jsx_factory: String,
    #[serde(
        rename = "jsxFragmentFactory",
        skip_serializing_if = "String::is_empty"
    )]
    pub jsx_fragment_factory: String,
    #[serde(rename = "jsxImportSource", skip_serializing_if = "String::is_empty")]
    pub jsx_import_source: String,
    #[serde(rename = "lib", skip_serializing_if = "Option::is_none")]
    pub lib: Option<Vec<String>>,
    #[serde(
        rename = "libReplacement",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub lib_replacement: Tristate,
    #[serde(rename = "locale", skip_serializing_if = "String::is_empty")]
    pub locale: String,
    #[serde(rename = "mapRoot", skip_serializing_if = "str::is_empty")]
    pub map_root: tspath::SourceMapLocation,
    #[serde(rename = "module", skip_serializing_if = "is_default")]
    pub module: ModuleKind,
    #[serde(rename = "moduleResolution", skip_serializing_if = "is_default")]
    pub module_resolution: ModuleResolutionKind,
    #[serde(rename = "moduleSuffixes", skip_serializing_if = "Option::is_none")]
    pub module_suffixes: Option<Vec<String>>,
    #[serde(rename = "moduleDetection", skip_serializing_if = "is_default")]
    pub module_detection: ModuleDetectionKind,
    #[serde(rename = "newLine", skip_serializing_if = "is_default")]
    pub new_line: NewLineKind,
    #[serde(rename = "noEmit", skip_serializing_if = "Tristate::is_unknown")]
    pub no_emit: Tristate,
    #[serde(rename = "noCheck", skip_serializing_if = "Tristate::is_unknown")]
    pub no_check: Tristate,
    #[serde(
        rename = "noErrorTruncation",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_error_truncation: Tristate,
    #[serde(
        rename = "noFallthroughCasesInSwitch",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_fallthrough_cases_in_switch: Tristate,
    #[serde(rename = "noImplicitAny", skip_serializing_if = "Tristate::is_unknown")]
    pub no_implicit_any: Tristate,
    #[serde(
        rename = "noImplicitThis",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_implicit_this: Tristate,
    #[serde(
        rename = "noImplicitReturns",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_implicit_returns: Tristate,
    #[serde(rename = "noEmitHelpers", skip_serializing_if = "Tristate::is_unknown")]
    pub no_emit_helpers: Tristate,
    #[serde(rename = "noLib", skip_serializing_if = "Tristate::is_unknown")]
    pub no_lib: Tristate,
    #[serde(
        rename = "noPropertyAccessFromIndexSignature",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_property_access_from_index_signature: Tristate,
    #[serde(
        rename = "noUncheckedIndexedAccess",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_unchecked_indexed_access: Tristate,
    #[serde(rename = "noEmitOnError", skip_serializing_if = "Tristate::is_unknown")]
    pub no_emit_on_error: Tristate,
    #[serde(
        rename = "noUnusedLocals",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_unused_locals: Tristate,
    #[serde(
        rename = "noUnusedParameters",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_unused_parameters: Tristate,
    #[serde(rename = "noResolve", skip_serializing_if = "Tristate::is_unknown")]
    pub no_resolve: Tristate,
    #[serde(
        rename = "noImplicitOverride",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_implicit_override: Tristate,
    #[serde(
        rename = "noUncheckedSideEffectImports",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_unchecked_side_effect_imports: Tristate,
    #[serde(
        rename = "outDir",
        skip_serializing_if = "str::is_empty",
        with = "rooted_directory_path_serde"
    )]
    pub out_dir: tspath::RootedDirectoryPath,
    // PORT: `*OrderedMap[string, []string]` — the nilable Option<Vec<String>>
    // values preserve Go's nil-vs-empty distinction inside `Equals`.
    #[serde(rename = "paths", skip_serializing_if = "Option::is_none")]
    pub paths: Option<OrderedMap<String, Option<Vec<String>>>>,
    // Plugins are parsed only so tools can report that native TypeScript does not support them.
    #[serde(rename = "plugins", skip_serializing_if = "Option::is_none")]
    pub plugins: Option<Vec<PluginImport>>,
    #[serde(
        rename = "preserveConstEnums",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub preserve_const_enums: Tristate,
    #[serde(
        rename = "preserveSymlinks",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub preserve_symlinks: Tristate,
    #[serde(
        rename = "project",
        skip_serializing_if = "str::is_empty",
        with = "rooted_path_serde"
    )]
    pub project: tspath::RootedPath,
    #[serde(
        rename = "resolveJsonModule",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub resolve_json_module: Tristate,
    #[serde(
        rename = "resolvePackageJsonExports",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub resolve_package_json_exports: Tristate,
    #[serde(
        rename = "resolvePackageJsonImports",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub resolve_package_json_imports: Tristate,
    #[serde(
        rename = "removeComments",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub remove_comments: Tristate,
    #[serde(
        rename = "rewriteRelativeImportExtensions",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub rewrite_relative_import_extensions: Tristate,
    #[serde(rename = "reactNamespace", skip_serializing_if = "String::is_empty")]
    pub react_namespace: String,
    #[serde(
        rename = "rootDir",
        skip_serializing_if = "str::is_empty",
        with = "rooted_directory_path_serde"
    )]
    pub root_dir: tspath::RootedDirectoryPath,
    #[serde(
        rename = "rootDirs",
        skip_serializing_if = "Option::is_none",
        with = "rooted_directory_path_vec_serde"
    )]
    pub root_dirs: Option<Vec<tspath::RootedDirectoryPath>>,
    #[serde(rename = "skipLibCheck", skip_serializing_if = "Tristate::is_unknown")]
    pub skip_lib_check: Tristate,
    #[serde(
        rename = "stableTypeOrdering",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub stable_type_ordering: Tristate,
    #[serde(rename = "strict", skip_serializing_if = "Tristate::is_unknown")]
    pub strict: Tristate,
    #[serde(
        rename = "strictBindCallApply",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub strict_bind_call_apply: Tristate,
    #[serde(
        rename = "strictBuiltinIteratorReturn",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub strict_builtin_iterator_return: Tristate,
    #[serde(
        rename = "strictFunctionTypes",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub strict_function_types: Tristate,
    #[serde(
        rename = "strictNullChecks",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub strict_null_checks: Tristate,
    #[serde(
        rename = "strictPropertyInitialization",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub strict_property_initialization: Tristate,
    #[serde(rename = "stripInternal", skip_serializing_if = "Tristate::is_unknown")]
    pub strip_internal: Tristate,
    #[serde(
        rename = "skipDefaultLibCheck",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub skip_default_lib_check: Tristate,
    #[serde(rename = "sourceMap", skip_serializing_if = "Tristate::is_unknown")]
    pub source_map: Tristate,
    #[serde(rename = "sourceRoot", skip_serializing_if = "str::is_empty")]
    pub source_root: tspath::SourceMapLocation,
    #[serde(
        rename = "suppressOutputPathCheck",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub suppress_output_path_check: Tristate,
    #[serde(rename = "target", skip_serializing_if = "is_default")]
    pub target: ScriptTarget,
    #[serde(
        rename = "traceResolution",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub trace_resolution: Tristate,
    #[serde(
        rename = "tsBuildInfoFile",
        skip_serializing_if = "str::is_empty",
        with = "rooted_file_path_serde"
    )]
    pub ts_build_info_file: tspath::RootedFilePath,
    #[serde(
        rename = "typeRoots",
        skip_serializing_if = "Option::is_none",
        with = "rooted_directory_path_vec_serde"
    )]
    pub type_roots: Option<Vec<tspath::RootedDirectoryPath>>,
    #[serde(rename = "types", skip_serializing_if = "Option::is_none")]
    pub types: Option<Vec<String>>,
    #[serde(
        rename = "useDefineForClassFields",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub use_define_for_class_fields: Tristate,
    #[serde(
        rename = "useUnknownInCatchVariables",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub use_unknown_in_catch_variables: Tristate,
    #[serde(
        rename = "verbatimModuleSyntax",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub verbatim_module_syntax: Tristate,
    #[serde(
        rename = "maxNodeModuleJsDepth",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_node_module_js_depth: Option<i32>,
    // Deprecated: Do not use outside of options parsing and validation.
    #[serde(
        rename = "allowSyntheticDefaultImports",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub allow_synthetic_default_imports: Tristate,
    // Deprecated: Do not use outside of options parsing and validation.
    #[serde(rename = "alwaysStrict", skip_serializing_if = "Tristate::is_unknown")]
    pub always_strict: Tristate,
    // Deprecated: Do not use outside of options parsing and validation.
    #[serde(
        rename = "baseUrl",
        skip_serializing_if = "str::is_empty",
        with = "rooted_directory_path_serde"
    )]
    pub base_url: tspath::RootedDirectoryPath,
    // Deprecated: Do not use outside of options parsing and validation.
    #[serde(
        rename = "downlevelIteration",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub downlevel_iteration: Tristate,
    // Deprecated: Do not use outside of options parsing and validation.
    #[serde(
        rename = "esModuleInterop",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub es_module_interop: Tristate,
    // Deprecated: Do not use outside of options parsing and validation.
    #[serde(
        rename = "outFile",
        skip_serializing_if = "str::is_empty",
        with = "rooted_file_path_serde"
    )]
    pub out_file: tspath::RootedFilePath,

    // Internal fields
    #[serde(
        rename = "configFilePath",
        skip_serializing_if = "str::is_empty",
        with = "rooted_file_path_serde"
    )]
    pub config_file_path: tspath::RootedFilePath,
    #[serde(
        rename = "noDtsResolution",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_dts_resolution: Tristate,
    #[serde(
        rename = "pathsBasePath",
        skip_serializing_if = "str::is_empty",
        with = "rooted_directory_path_serde"
    )]
    pub paths_base_path: tspath::RootedDirectoryPath,
    #[serde(rename = "diagnostics", skip_serializing_if = "Tristate::is_unknown")]
    pub diagnostics: Tristate,
    #[serde(
        rename = "extendedDiagnostics",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub extended_diagnostics: Tristate,
    #[serde(
        rename = "generateCpuProfile",
        skip_serializing_if = "str::is_empty",
        with = "rooted_file_path_serde"
    )]
    pub generate_cpu_profile: tspath::RootedFilePath,
    #[serde(
        rename = "generateTrace",
        skip_serializing_if = "str::is_empty",
        with = "rooted_directory_path_serde"
    )]
    pub generate_trace: tspath::RootedDirectoryPath,
    #[serde(
        rename = "listEmittedFiles",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub list_emitted_files: Tristate,
    #[serde(rename = "listFiles", skip_serializing_if = "Tristate::is_unknown")]
    pub list_files: Tristate,
    #[serde(rename = "explainFiles", skip_serializing_if = "Tristate::is_unknown")]
    pub explain_files: Tristate,
    #[serde(rename = "listFilesOnly", skip_serializing_if = "Tristate::is_unknown")]
    pub list_files_only: Tristate,
    #[serde(
        rename = "noEmitForJsFiles",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub no_emit_for_js_files: Tristate,
    #[serde(
        rename = "preserveWatchOutput",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub preserve_watch_output: Tristate,
    #[serde(rename = "pretty", skip_serializing_if = "Tristate::is_unknown")]
    pub pretty: Tristate,
    #[serde(rename = "version", skip_serializing_if = "Tristate::is_unknown")]
    pub version: Tristate,
    #[serde(rename = "watch", skip_serializing_if = "Tristate::is_unknown")]
    pub watch: Tristate,
    #[serde(rename = "showConfig", skip_serializing_if = "Tristate::is_unknown")]
    pub show_config: Tristate,
    #[serde(rename = "build", skip_serializing_if = "Tristate::is_unknown")]
    pub build: Tristate,
    #[serde(rename = "help", skip_serializing_if = "Tristate::is_unknown")]
    pub help: Tristate,
    #[serde(rename = "all", skip_serializing_if = "Tristate::is_unknown")]
    pub all: Tristate,
    #[serde(
        rename = "runExternalCode",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub run_external_code: Tristate,
    #[serde(
        rename = "pprofDir",
        skip_serializing_if = "str::is_empty",
        with = "rooted_directory_path_serde"
    )]
    pub pprof_dir: tspath::RootedDirectoryPath,
    #[serde(
        rename = "singleThreaded",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub single_threaded: Tristate,
    #[serde(rename = "quiet", skip_serializing_if = "Tristate::is_unknown")]
    pub quiet: Tristate,
    #[serde(rename = "checkers", skip_serializing_if = "Option::is_none")]
    pub checkers: Option<i32>,
}

// PORT: Go's `Clone()` copies slice headers and pointers (sharing the same
// backing storage); `#[derive(Clone)]` performs a deep copy of the Vec,
// Option and OrderedMap fields. Both produce an independently mutable
// options struct; the only observable difference is Go's `same()`-style
// identity, which `CompilerOptions.Equals` does not depend on.

// Equals reports whether all stored option values are equal, including nil versus empty collections.
// Paths are compared by ordered entries, ignoring backing-storage allocation.
//
// PORT: nilable receivers become `Option<&CompilerOptions>` parameters.
// `(a == nil) != (b == nil) || !slices.Equal(a, b)` collapses to `a != b`
// for `Option<Vec<_>>` fields, and `*int` nil-or-value inequality collapses
// to `Option<i32>` inequality.
impl CompilerOptions {
    pub fn equals(options: Option<&CompilerOptions>, other: Option<&CompilerOptions>) -> bool {
        match (options, other) {
            (Some(a), Some(b)) if std::ptr::eq(a, b) => return true,
            (None, None) => return true,
            (None, _) | (_, None) => return false,
            _ => {}
        }
        let (Some(options), Some(other)) = (options, other) else {
            unreachable!()
        };

        if options.allow_js != other.allow_js {
            return false;
        }
        if options.allow_arbitrary_extensions != other.allow_arbitrary_extensions {
            return false;
        }
        if options.allow_importing_ts_extensions != other.allow_importing_ts_extensions {
            return false;
        }
        if options.allow_non_ts_extensions != other.allow_non_ts_extensions {
            return false;
        }
        if options.allow_umd_global_access != other.allow_umd_global_access {
            return false;
        }
        if options.allow_unreachable_code != other.allow_unreachable_code {
            return false;
        }
        if options.allow_unused_labels != other.allow_unused_labels {
            return false;
        }
        if options.assume_changes_only_affect_direct_dependencies
            != other.assume_changes_only_affect_direct_dependencies
        {
            return false;
        }
        if options.check_js != other.check_js {
            return false;
        }
        if options.custom_conditions != other.custom_conditions {
            return false;
        }
        if options.composite != other.composite {
            return false;
        }
        if options.emit_declaration_only != other.emit_declaration_only {
            return false;
        }
        if options.emit_bom != other.emit_bom {
            return false;
        }
        if options.emit_decorator_metadata != other.emit_decorator_metadata {
            return false;
        }
        if options.declaration != other.declaration {
            return false;
        }
        if options.declaration_dir != other.declaration_dir {
            return false;
        }
        if options.declaration_map != other.declaration_map {
            return false;
        }
        if options.deduplicate_packages != other.deduplicate_packages {
            return false;
        }
        if options.disable_size_limit != other.disable_size_limit {
            return false;
        }
        if options.disable_source_of_project_reference_redirect
            != other.disable_source_of_project_reference_redirect
        {
            return false;
        }
        if options.disable_solution_searching != other.disable_solution_searching {
            return false;
        }
        if options.disable_referenced_project_load != other.disable_referenced_project_load {
            return false;
        }
        if options.erasable_syntax_only != other.erasable_syntax_only {
            return false;
        }
        if options.exact_optional_property_types != other.exact_optional_property_types {
            return false;
        }
        if options.experimental_decorators != other.experimental_decorators {
            return false;
        }
        if options.force_consistent_casing_in_file_names
            != other.force_consistent_casing_in_file_names
        {
            return false;
        }
        if options.isolated_modules != other.isolated_modules {
            return false;
        }
        if options.isolated_declarations != other.isolated_declarations {
            return false;
        }
        if options.ignore_config != other.ignore_config {
            return false;
        }
        if options.ignore_deprecations != other.ignore_deprecations {
            return false;
        }
        if options.import_helpers != other.import_helpers {
            return false;
        }
        if options.inline_source_map != other.inline_source_map {
            return false;
        }
        if options.inline_sources != other.inline_sources {
            return false;
        }
        if options.init != other.init {
            return false;
        }
        if options.incremental != other.incremental {
            return false;
        }
        if options.jsx != other.jsx {
            return false;
        }
        if options.jsx_factory != other.jsx_factory {
            return false;
        }
        if options.jsx_fragment_factory != other.jsx_fragment_factory {
            return false;
        }
        if options.jsx_import_source != other.jsx_import_source {
            return false;
        }
        if options.lib != other.lib {
            return false;
        }
        if options.lib_replacement != other.lib_replacement {
            return false;
        }
        if options.locale != other.locale {
            return false;
        }
        if options.map_root != other.map_root {
            return false;
        }
        if options.module != other.module {
            return false;
        }
        if options.module_resolution != other.module_resolution {
            return false;
        }
        if options.module_suffixes != other.module_suffixes {
            return false;
        }
        if options.module_detection != other.module_detection {
            return false;
        }
        if options.new_line != other.new_line {
            return false;
        }
        if options.no_emit != other.no_emit {
            return false;
        }
        if options.no_check != other.no_check {
            return false;
        }
        if options.no_error_truncation != other.no_error_truncation {
            return false;
        }
        if options.no_fallthrough_cases_in_switch != other.no_fallthrough_cases_in_switch {
            return false;
        }
        if options.no_implicit_any != other.no_implicit_any {
            return false;
        }
        if options.no_implicit_this != other.no_implicit_this {
            return false;
        }
        if options.no_implicit_returns != other.no_implicit_returns {
            return false;
        }
        if options.no_emit_helpers != other.no_emit_helpers {
            return false;
        }
        if options.no_lib != other.no_lib {
            return false;
        }
        if options.no_property_access_from_index_signature
            != other.no_property_access_from_index_signature
        {
            return false;
        }
        if options.no_unchecked_indexed_access != other.no_unchecked_indexed_access {
            return false;
        }
        if options.no_emit_on_error != other.no_emit_on_error {
            return false;
        }
        if options.no_unused_locals != other.no_unused_locals {
            return false;
        }
        if options.no_unused_parameters != other.no_unused_parameters {
            return false;
        }
        if options.no_resolve != other.no_resolve {
            return false;
        }
        if options.no_implicit_override != other.no_implicit_override {
            return false;
        }
        if options.no_unchecked_side_effect_imports != other.no_unchecked_side_effect_imports {
            return false;
        }
        if options.out_dir != other.out_dir {
            return false;
        }
        if !OrderedMap::equal_func(options.paths.as_ref(), other.paths.as_ref(), |a, b| {
            a.is_none() == b.is_none() && a == b
        }) {
            return false;
        }
        if options.plugins != other.plugins {
            return false;
        }
        if options.preserve_const_enums != other.preserve_const_enums {
            return false;
        }
        if options.preserve_symlinks != other.preserve_symlinks {
            return false;
        }
        if options.project != other.project {
            return false;
        }
        if options.resolve_json_module != other.resolve_json_module {
            return false;
        }
        if options.resolve_package_json_exports != other.resolve_package_json_exports {
            return false;
        }
        if options.resolve_package_json_imports != other.resolve_package_json_imports {
            return false;
        }
        if options.remove_comments != other.remove_comments {
            return false;
        }
        if options.rewrite_relative_import_extensions != other.rewrite_relative_import_extensions {
            return false;
        }
        if options.react_namespace != other.react_namespace {
            return false;
        }
        if options.root_dir != other.root_dir {
            return false;
        }
        if options.root_dirs != other.root_dirs {
            return false;
        }
        if options.skip_lib_check != other.skip_lib_check {
            return false;
        }
        if options.stable_type_ordering != other.stable_type_ordering {
            return false;
        }
        if options.strict != other.strict {
            return false;
        }
        if options.strict_bind_call_apply != other.strict_bind_call_apply {
            return false;
        }
        if options.strict_builtin_iterator_return != other.strict_builtin_iterator_return {
            return false;
        }
        if options.strict_function_types != other.strict_function_types {
            return false;
        }
        if options.strict_null_checks != other.strict_null_checks {
            return false;
        }
        if options.strict_property_initialization != other.strict_property_initialization {
            return false;
        }
        if options.strip_internal != other.strip_internal {
            return false;
        }
        if options.skip_default_lib_check != other.skip_default_lib_check {
            return false;
        }
        if options.source_map != other.source_map {
            return false;
        }
        if options.source_root != other.source_root {
            return false;
        }
        if options.suppress_output_path_check != other.suppress_output_path_check {
            return false;
        }
        if options.target != other.target {
            return false;
        }
        if options.trace_resolution != other.trace_resolution {
            return false;
        }
        if options.ts_build_info_file != other.ts_build_info_file {
            return false;
        }
        if options.type_roots != other.type_roots {
            return false;
        }
        if options.types != other.types {
            return false;
        }
        if options.use_define_for_class_fields != other.use_define_for_class_fields {
            return false;
        }
        if options.use_unknown_in_catch_variables != other.use_unknown_in_catch_variables {
            return false;
        }
        if options.verbatim_module_syntax != other.verbatim_module_syntax {
            return false;
        }
        if options.max_node_module_js_depth != other.max_node_module_js_depth {
            return false;
        }
        if options.allow_synthetic_default_imports != other.allow_synthetic_default_imports {
            return false;
        }
        if options.always_strict != other.always_strict {
            return false;
        }
        if options.base_url != other.base_url {
            return false;
        }
        if options.downlevel_iteration != other.downlevel_iteration {
            return false;
        }
        if options.es_module_interop != other.es_module_interop {
            return false;
        }
        if options.out_file != other.out_file {
            return false;
        }
        if options.config_file_path != other.config_file_path {
            return false;
        }
        if options.no_dts_resolution != other.no_dts_resolution {
            return false;
        }
        if options.paths_base_path != other.paths_base_path {
            return false;
        }
        if options.diagnostics != other.diagnostics {
            return false;
        }
        if options.extended_diagnostics != other.extended_diagnostics {
            return false;
        }
        if options.generate_cpu_profile != other.generate_cpu_profile {
            return false;
        }
        if options.generate_trace != other.generate_trace {
            return false;
        }
        if options.list_emitted_files != other.list_emitted_files {
            return false;
        }
        if options.list_files != other.list_files {
            return false;
        }
        if options.explain_files != other.explain_files {
            return false;
        }
        if options.list_files_only != other.list_files_only {
            return false;
        }
        if options.no_emit_for_js_files != other.no_emit_for_js_files {
            return false;
        }
        if options.preserve_watch_output != other.preserve_watch_output {
            return false;
        }
        if options.pretty != other.pretty {
            return false;
        }
        if options.version != other.version {
            return false;
        }
        if options.watch != other.watch {
            return false;
        }
        if options.show_config != other.show_config {
            return false;
        }
        if options.build != other.build {
            return false;
        }
        if options.help != other.help {
            return false;
        }
        if options.all != other.all {
            return false;
        }
        if options.run_external_code != other.run_external_code {
            return false;
        }
        if options.pprof_dir != other.pprof_dir {
            return false;
        }
        if options.single_threaded != other.single_threaded {
            return false;
        }
        if options.quiet != other.quiet {
            return false;
        }
        if options.checkers != other.checkers {
            return false;
        }
        true
    }
}

// PORT: `into`/`try_from` serialize these enums as their Go `int32` ordinals.
// Deserialization rejects out-of-range values; Go would accept them into the
// open `int32` newtype — a malformed-JSON-only divergence.

macro_rules! serde_i32_enum {
    ($name:ident, $($variant:ident = $value:expr),+ $(,)?) => {
        impl From<$name> for i32 {
            fn from(v: $name) -> i32 {
                v as i32
            }
        }

        impl TryFrom<i32> for $name {
            type Error = String;
            fn try_from(value: i32) -> Result<Self, Self::Error> {
                match value {
                    $($value => Ok(Self::$variant),)+
                    _ => Err(format!("invalid value {value} for {}", stringify!($name))),
                }
            }
        }
    };
}

#[derive(
    Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize,
)]
#[serde(into = "i32", try_from = "i32")]
#[repr(i32)]
pub enum ModuleDetectionKind {
    #[default]
    None = 0,
    Auto = 1,
    Legacy = 2,
    Force = 3,
}
serde_i32_enum!(
    ModuleDetectionKind,
    None = 0,
    Auto = 1,
    Legacy = 2,
    Force = 3
);

#[derive(
    Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize,
)]
#[serde(into = "i32", try_from = "i32")]
#[repr(i32)]
pub enum ModuleKind {
    #[default]
    None = 0,
    CommonJS = 1,
    // Deprecated: Do not use outside of options parsing and validation.
    AMD = 2,
    // Deprecated: Do not use outside of options parsing and validation.
    UMD = 3,
    // Deprecated: Do not use outside of options parsing and validation.
    System = 4,
    // NOTE: ES module kinds should be contiguous to more easily check whether a module kind is *any* ES module kind.
    // Non-ES module kinds should not come between ES2015 (the earliest ES module kind) and ESNext (the last ES
    // module kind).
    ES2015 = 5,
    ES2020 = 6,
    ES2022 = 7,
    ESNext = 99,
    // Node16+ is an amalgam of commonjs (albeit updated) and es2022+, and represents a distinct module system from es2020/esnext
    Node16 = 100,
    Node18 = 101,
    Node20 = 102,
    NodeNext = 199,
    // Emit as written
    Preserve = 200,
}
serde_i32_enum!(
    ModuleKind,
    None = 0,
    CommonJS = 1,
    AMD = 2,
    UMD = 3,
    System = 4,
    ES2015 = 5,
    ES2020 = 6,
    ES2022 = 7,
    ESNext = 99,
    Node16 = 100,
    Node18 = 101,
    Node20 = 102,
    NodeNext = 199,
    Preserve = 200,
);

#[derive(
    Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize,
)]
#[serde(into = "i32", try_from = "i32")]
#[repr(i32)]
pub enum ModuleResolutionKind {
    #[default]
    Unknown = 0,
    // Deprecated: Do not use outside of options parsing and validation.
    Classic = 1,
    // Deprecated: Do not use outside of options parsing and validation.
    Node10 = 2,
    // Starting with node16, node's module resolver has significant departures from traditional cjs resolution
    // to better support ECMAScript modules and their use within node - however more features are still being added.
    // TypeScript's Node ESM support was introduced after Node 12 went end-of-life, and Node 14 is the earliest stable
    // version that supports both pattern trailers - *but*, Node 16 is the first version that also supports ECMAScript 2022.
    // In turn, we offer both a `NodeNext` moving resolution target, and a `Node16` version-anchored resolution target
    Node16 = 3,
    NodeNext = 99, // Not simply `Node16` so that compiled code linked against TS can use the `Next` value reliably (same as with `ModuleKind`)
    Bundler = 100,
}
serde_i32_enum!(
    ModuleResolutionKind,
    Unknown = 0,
    Classic = 1,
    Node10 = 2,
    Node16 = 3,
    NodeNext = 99,
    Bundler = 100,
);

#[derive(
    Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize,
)]
#[serde(into = "i32", try_from = "i32")]
#[repr(i32)]
pub enum NewLineKind {
    #[default]
    None = 0,
    CRLF = 1,
    LF = 2,
}
serde_i32_enum!(NewLineKind, None = 0, CRLF = 1, LF = 2);

#[derive(
    Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize,
)]
#[serde(into = "i32", try_from = "i32")]
#[repr(i32)]
pub enum ScriptTarget {
    #[default]
    None = 0,
    // Deprecated: Do not use outside of options parsing and validation.
    ES5 = 1,
    ES2015 = 2,
    ES2016 = 3,
    ES2017 = 4,
    ES2018 = 5,
    ES2019 = 6,
    ES2020 = 7,
    ES2021 = 8,
    ES2022 = 9,
    ES2023 = 10,
    ES2024 = 11,
    ES2025 = 12,
    ES2026 = 13,
    ESNext = 99,
    JSON = 100,
}
serde_i32_enum!(
    ScriptTarget,
    None = 0,
    ES5 = 1,
    ES2015 = 2,
    ES2016 = 3,
    ES2017 = 4,
    ES2018 = 5,
    ES2019 = 6,
    ES2020 = 7,
    ES2021 = 8,
    ES2022 = 9,
    ES2023 = 10,
    ES2024 = 11,
    ES2025 = 12,
    ES2026 = 13,
    ESNext = 99,
    JSON = 100,
);

impl ScriptTarget {
    pub const LATEST: ScriptTarget = ScriptTarget::ESNext;
    pub const LATEST_STANDARD: ScriptTarget = ScriptTarget::ES2026;
}

#[derive(
    Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize,
)]
#[serde(into = "i32", try_from = "i32")]
#[repr(i32)]
pub enum JsxEmit {
    #[default]
    None = 0,
    Preserve = 1,
    React = 2,
    ReactNative = 3,
    ReactJSX = 4,
    ReactJSXDev = 5,
}
serde_i32_enum!(
    JsxEmit,
    None = 0,
    Preserve = 1,
    React = 2,
    ReactNative = 3,
    ReactJSX = 4,
    ReactJSXDev = 5,
);

// PORT: `map[ModuleKind]ModuleResolutionKind` becomes a LazyLock map;
// lookups `.get(&kind).copied().unwrap_or_default()` reproduce Go's
// missing-key zero value (ModuleResolutionKindUnknown).
pub static MODULE_KIND_TO_MODULE_RESOLUTION_KIND: LazyLock<
    rustc_hash::FxHashMap<ModuleKind, ModuleResolutionKind>,
> = LazyLock::new(|| {
    let mut m = rustc_hash::FxHashMap::default();
    m.insert(ModuleKind::Node16, ModuleResolutionKind::Node16);
    m.insert(ModuleKind::NodeNext, ModuleResolutionKind::NodeNext);
    m
});

// PORT: Go's `String()` methods panic on the zero value and on unhandled
// cases; `Display` reproduces that.
impl std::fmt::Display for ModuleResolutionKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ModuleResolutionKind::Unknown => {
                panic!("should not use zero value of ModuleResolutionKind")
            }
            ModuleResolutionKind::Classic => f.write_str("Classic"),
            ModuleResolutionKind::Node10 => f.write_str("Node10"),
            ModuleResolutionKind::Node16 => f.write_str("Node16"),
            ModuleResolutionKind::NodeNext => f.write_str("NodeNext"),
            ModuleResolutionKind::Bundler => f.write_str("Bundler"),
        }
    }
}

impl std::fmt::Display for JsxEmit {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            JsxEmit::None => panic!("should not use zero value of JsxEmit"),
            JsxEmit::Preserve => f.write_str("preserve"),
            JsxEmit::React => f.write_str("react"),
            JsxEmit::ReactNative => f.write_str("react-native"),
            JsxEmit::ReactJSX => f.write_str("react-jsx"),
            JsxEmit::ReactJSXDev => f.write_str("react-jsxdev"),
        }
    }
}

// PORT: Go's `_ noCopy` marker is unneeded.
#[derive(Clone, Default, Debug, Serialize, Deserialize)]
#[serde(default)]
pub struct TypeAcquisition {
    #[serde(rename = "enable", skip_serializing_if = "Tristate::is_unknown")]
    pub enable: Tristate,
    #[serde(rename = "include", skip_serializing_if = "Option::is_none")]
    pub include: Option<Vec<String>>,
    #[serde(rename = "exclude", skip_serializing_if = "Option::is_none")]
    pub exclude: Option<Vec<String>>,
    #[serde(
        rename = "disableFilenameBasedTypeAcquisition",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub disable_filename_based_type_acquisition: Tristate,
}

// PORT: Go's `_ noCopy` marker is unneeded.
#[derive(Clone, Default, Debug, Serialize, Deserialize)]
#[serde(default)]
pub struct BuildOptions {
    #[serde(rename = "dry", skip_serializing_if = "Tristate::is_unknown")]
    pub dry: Tristate,
    #[serde(rename = "force", skip_serializing_if = "Tristate::is_unknown")]
    pub force: Tristate,
    #[serde(rename = "verbose", skip_serializing_if = "Tristate::is_unknown")]
    pub verbose: Tristate,
    #[serde(rename = "builders", skip_serializing_if = "Option::is_none")]
    pub builders: Option<i32>,
    #[serde(
        rename = "stopBuildOnErrors",
        skip_serializing_if = "Tristate::is_unknown"
    )]
    pub stop_build_on_errors: Tristate,

    // Internal fields
    #[serde(rename = "clean", skip_serializing_if = "Tristate::is_unknown")]
    pub clean: Tristate,
}
