// Code generated by rust/tools/gen-options from rust/tools/gen-options/data/options-model.json. DO NOT EDIT.
// Rust mirror of tsc/internal/core/options_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763
// (upstream: tools/scripts/tsc/generate-options.ts emits that file from
// tools/scripts/tsc/options.ts — the same rows/options data mirrored here;
// per SPEC §6 the Go output is never a generation input, only the parity
// baseline for the tests at the bottom of this file).
//
// PORT notes (vs options_generated.go):
//   - Go's `noCopy` embed and json tags have no Rust counterpart; dropped.
//   - Go `*int` -> `Option<i64>` (Go int is 64-bit here).
//   - Go's slice nil-vs-empty distinction collapses: nil -> empty Vec, and
//     the generated Equals compares Vec values (Go's
//     `(a == nil) != (b == nil) || !slices.Equal(a, b)` reduces to `a != b`).
//   - `Clone` (Go's generated method) -> `#[derive(Clone)]` (same shallow,
//     field-by-field copy semantics).
//   - Value-alias enum members (`ScriptTargetLatest` = `ScriptTargetESNext`)
//     become associated consts; Rust enums cannot share discriminants.
//   - Go's panicking `String()` methods become `Display` impls with identical
//     outputs; zero values panic, exactly as in Go.
//   - Derived `PartialOrd`/`Ord` match the numeric order (validated: member
//     values are monotonic in declaration order).

use std::fmt;

use tsc_collections::OrderedMap;
use tsc_tspath::{RootedDirectoryPath, RootedFilePath, RootedPath, SourceMapLocation};

use crate::tristate::Tristate;

/// Go: `type PluginImport struct { Name string }`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PluginImport {
    pub name: String,
}

/// CompilerOptions contains the compiler options exposed by the API.
#[derive(Clone, Debug, Default)]
pub struct CompilerOptions {
    pub allow_js: Tristate,
    pub allow_arbitrary_extensions: Tristate,
    pub allow_importing_ts_extensions: Tristate,
    pub allow_non_ts_extensions: Tristate,
    pub allow_umd_global_access: Tristate,
    pub allow_unreachable_code: Tristate,
    pub allow_unused_labels: Tristate,
    pub assume_changes_only_affect_direct_dependencies: Tristate,
    pub check_js: Tristate,
    pub custom_conditions: Vec<String>,
    pub composite: Tristate,
    pub emit_declaration_only: Tristate,
    pub emit_bom: Tristate,
    pub emit_decorator_metadata: Tristate,
    pub declaration: Tristate,
    pub declaration_dir: RootedDirectoryPath,
    pub declaration_map: Tristate,
    pub deduplicate_packages: Tristate,
    pub disable_size_limit: Tristate,
    pub disable_source_of_project_reference_redirect: Tristate,
    pub disable_solution_searching: Tristate,
    pub disable_referenced_project_load: Tristate,
    pub erasable_syntax_only: Tristate,
    pub exact_optional_property_types: Tristate,
    pub experimental_decorators: Tristate,
    pub force_consistent_casing_in_file_names: Tristate,
    pub isolated_modules: Tristate,
    pub isolated_declarations: Tristate,
    pub ignore_config: Tristate,
    pub ignore_deprecations: String,
    pub import_helpers: Tristate,
    pub inline_source_map: Tristate,
    pub inline_sources: Tristate,
    pub init: Tristate,
    pub incremental: Tristate,
    pub jsx: JsxEmit,
    pub jsx_factory: String,
    pub jsx_fragment_factory: String,
    pub jsx_import_source: String,
    pub lib: Vec<String>,
    pub lib_replacement: Tristate,
    pub locale: String,
    pub map_root: SourceMapLocation,
    pub module: ModuleKind,
    pub module_resolution: ModuleResolutionKind,
    pub module_suffixes: Vec<String>,
    pub module_detection: ModuleDetectionKind,
    pub new_line: NewLineKind,
    pub no_emit: Tristate,
    pub no_check: Tristate,
    pub no_error_truncation: Tristate,
    pub no_fallthrough_cases_in_switch: Tristate,
    pub no_implicit_any: Tristate,
    pub no_implicit_this: Tristate,
    pub no_implicit_returns: Tristate,
    pub no_emit_helpers: Tristate,
    pub no_lib: Tristate,
    pub no_property_access_from_index_signature: Tristate,
    pub no_unchecked_indexed_access: Tristate,
    pub no_emit_on_error: Tristate,
    pub no_unused_locals: Tristate,
    pub no_unused_parameters: Tristate,
    pub no_resolve: Tristate,
    pub no_implicit_override: Tristate,
    pub no_unchecked_side_effect_imports: Tristate,
    pub out_dir: RootedDirectoryPath,
    pub paths: Option<OrderedMap<String, Vec<String>>>,
    /// Plugins are parsed only so tools can report that native TypeScript does not support them.
    pub plugins: Vec<PluginImport>,
    pub preserve_const_enums: Tristate,
    pub preserve_symlinks: Tristate,
    pub project: RootedPath,
    pub resolve_json_module: Tristate,
    pub resolve_package_json_exports: Tristate,
    pub resolve_package_json_imports: Tristate,
    pub remove_comments: Tristate,
    pub rewrite_relative_import_extensions: Tristate,
    pub react_namespace: String,
    pub root_dir: RootedDirectoryPath,
    pub root_dirs: Vec<RootedDirectoryPath>,
    pub skip_lib_check: Tristate,
    pub stable_type_ordering: Tristate,
    pub strict: Tristate,
    pub strict_bind_call_apply: Tristate,
    pub strict_builtin_iterator_return: Tristate,
    pub strict_function_types: Tristate,
    pub strict_null_checks: Tristate,
    pub strict_property_initialization: Tristate,
    pub strip_internal: Tristate,
    pub skip_default_lib_check: Tristate,
    pub source_map: Tristate,
    pub source_root: SourceMapLocation,
    pub suppress_output_path_check: Tristate,
    pub target: ScriptTarget,
    pub trace_resolution: Tristate,
    pub ts_build_info_file: RootedFilePath,
    pub type_roots: Vec<RootedDirectoryPath>,
    pub types: Vec<String>,
    pub use_define_for_class_fields: Tristate,
    pub use_unknown_in_catch_variables: Tristate,
    pub verbatim_module_syntax: Tristate,
    pub max_node_module_js_depth: Option<i64>,
    /// Deprecated: Do not use outside of options parsing and validation.
    pub allow_synthetic_default_imports: Tristate,
    /// Deprecated: Do not use outside of options parsing and validation.
    pub always_strict: Tristate,
    /// Deprecated: Do not use outside of options parsing and validation.
    pub base_url: RootedDirectoryPath,
    /// Deprecated: Do not use outside of options parsing and validation.
    pub downlevel_iteration: Tristate,
    /// Deprecated: Do not use outside of options parsing and validation.
    pub es_module_interop: Tristate,
    /// Deprecated: Do not use outside of options parsing and validation.
    pub out_file: RootedFilePath,

    // Internal fields
    pub config_file_path: RootedFilePath,
    pub no_dts_resolution: Tristate,
    pub paths_base_path: RootedDirectoryPath,
    pub diagnostics: Tristate,
    pub extended_diagnostics: Tristate,
    pub generate_cpu_profile: RootedFilePath,
    pub generate_trace: RootedDirectoryPath,
    pub list_emitted_files: Tristate,
    pub list_files: Tristate,
    pub explain_files: Tristate,
    pub list_files_only: Tristate,
    pub no_emit_for_js_files: Tristate,
    pub preserve_watch_output: Tristate,
    pub pretty: Tristate,
    pub version: Tristate,
    pub watch: Tristate,
    pub show_config: Tristate,
    pub build: Tristate,
    pub help: Tristate,
    pub all: Tristate,
    pub run_external_code: Tristate,
    pub pprof_dir: RootedDirectoryPath,
    pub single_threaded: Tristate,
    pub quiet: Tristate,
    pub checkers: Option<i64>,
}

// Clone creates a shallow copy of the CompilerOptions.
// PORT: Go's generated `Clone` field-by-field copy -> `#[derive(Clone)]`.
impl CompilerOptions {
    /// Equals reports whether all stored option values are equal, including nil versus empty collections.
    /// Paths are compared by ordered entries, ignoring backing-storage allocation.
    ///
    /// PORT: Go's generated `Equals` is mirrored field-for-field in declaration
    /// order. The Go slice nil-vs-empty distinction collapses (fields are
    /// plain `Vec`s, so `(a == nil) != (b == nil) || !slices.Equal(a, b)`
    /// reduces to `a != b`); the `*int` and `Paths` nil handling is exact via
    /// `Option`. Go's `options == other` pointer shortcut has no counterpart.
    pub fn equals(&self, other: &CompilerOptions) -> bool {
        if self.allow_js != other.allow_js {
            return false;
        }
        if self.allow_arbitrary_extensions != other.allow_arbitrary_extensions {
            return false;
        }
        if self.allow_importing_ts_extensions != other.allow_importing_ts_extensions {
            return false;
        }
        if self.allow_non_ts_extensions != other.allow_non_ts_extensions {
            return false;
        }
        if self.allow_umd_global_access != other.allow_umd_global_access {
            return false;
        }
        if self.allow_unreachable_code != other.allow_unreachable_code {
            return false;
        }
        if self.allow_unused_labels != other.allow_unused_labels {
            return false;
        }
        if self.assume_changes_only_affect_direct_dependencies
            != other.assume_changes_only_affect_direct_dependencies
        {
            return false;
        }
        if self.check_js != other.check_js {
            return false;
        }
        if self.custom_conditions != other.custom_conditions {
            return false;
        }
        if self.composite != other.composite {
            return false;
        }
        if self.emit_declaration_only != other.emit_declaration_only {
            return false;
        }
        if self.emit_bom != other.emit_bom {
            return false;
        }
        if self.emit_decorator_metadata != other.emit_decorator_metadata {
            return false;
        }
        if self.declaration != other.declaration {
            return false;
        }
        if self.declaration_dir != other.declaration_dir {
            return false;
        }
        if self.declaration_map != other.declaration_map {
            return false;
        }
        if self.deduplicate_packages != other.deduplicate_packages {
            return false;
        }
        if self.disable_size_limit != other.disable_size_limit {
            return false;
        }
        if self.disable_source_of_project_reference_redirect
            != other.disable_source_of_project_reference_redirect
        {
            return false;
        }
        if self.disable_solution_searching != other.disable_solution_searching {
            return false;
        }
        if self.disable_referenced_project_load != other.disable_referenced_project_load {
            return false;
        }
        if self.erasable_syntax_only != other.erasable_syntax_only {
            return false;
        }
        if self.exact_optional_property_types != other.exact_optional_property_types {
            return false;
        }
        if self.experimental_decorators != other.experimental_decorators {
            return false;
        }
        if self.force_consistent_casing_in_file_names != other.force_consistent_casing_in_file_names
        {
            return false;
        }
        if self.isolated_modules != other.isolated_modules {
            return false;
        }
        if self.isolated_declarations != other.isolated_declarations {
            return false;
        }
        if self.ignore_config != other.ignore_config {
            return false;
        }
        if self.ignore_deprecations != other.ignore_deprecations {
            return false;
        }
        if self.import_helpers != other.import_helpers {
            return false;
        }
        if self.inline_source_map != other.inline_source_map {
            return false;
        }
        if self.inline_sources != other.inline_sources {
            return false;
        }
        if self.init != other.init {
            return false;
        }
        if self.incremental != other.incremental {
            return false;
        }
        if self.jsx != other.jsx {
            return false;
        }
        if self.jsx_factory != other.jsx_factory {
            return false;
        }
        if self.jsx_fragment_factory != other.jsx_fragment_factory {
            return false;
        }
        if self.jsx_import_source != other.jsx_import_source {
            return false;
        }
        if self.lib != other.lib {
            return false;
        }
        if self.lib_replacement != other.lib_replacement {
            return false;
        }
        if self.locale != other.locale {
            return false;
        }
        if self.map_root != other.map_root {
            return false;
        }
        if self.module != other.module {
            return false;
        }
        if self.module_resolution != other.module_resolution {
            return false;
        }
        if self.module_suffixes != other.module_suffixes {
            return false;
        }
        if self.module_detection != other.module_detection {
            return false;
        }
        if self.new_line != other.new_line {
            return false;
        }
        if self.no_emit != other.no_emit {
            return false;
        }
        if self.no_check != other.no_check {
            return false;
        }
        if self.no_error_truncation != other.no_error_truncation {
            return false;
        }
        if self.no_fallthrough_cases_in_switch != other.no_fallthrough_cases_in_switch {
            return false;
        }
        if self.no_implicit_any != other.no_implicit_any {
            return false;
        }
        if self.no_implicit_this != other.no_implicit_this {
            return false;
        }
        if self.no_implicit_returns != other.no_implicit_returns {
            return false;
        }
        if self.no_emit_helpers != other.no_emit_helpers {
            return false;
        }
        if self.no_lib != other.no_lib {
            return false;
        }
        if self.no_property_access_from_index_signature
            != other.no_property_access_from_index_signature
        {
            return false;
        }
        if self.no_unchecked_indexed_access != other.no_unchecked_indexed_access {
            return false;
        }
        if self.no_emit_on_error != other.no_emit_on_error {
            return false;
        }
        if self.no_unused_locals != other.no_unused_locals {
            return false;
        }
        if self.no_unused_parameters != other.no_unused_parameters {
            return false;
        }
        if self.no_resolve != other.no_resolve {
            return false;
        }
        if self.no_implicit_override != other.no_implicit_override {
            return false;
        }
        if self.no_unchecked_side_effect_imports != other.no_unchecked_side_effect_imports {
            return false;
        }
        if self.out_dir != other.out_dir {
            return false;
        }
        if !OrderedMap::equal_func(self.paths.as_ref(), other.paths.as_ref(), |a, b| a == b) {
            return false;
        }
        if self.plugins != other.plugins {
            return false;
        }
        if self.preserve_const_enums != other.preserve_const_enums {
            return false;
        }
        if self.preserve_symlinks != other.preserve_symlinks {
            return false;
        }
        if self.project != other.project {
            return false;
        }
        if self.resolve_json_module != other.resolve_json_module {
            return false;
        }
        if self.resolve_package_json_exports != other.resolve_package_json_exports {
            return false;
        }
        if self.resolve_package_json_imports != other.resolve_package_json_imports {
            return false;
        }
        if self.remove_comments != other.remove_comments {
            return false;
        }
        if self.rewrite_relative_import_extensions != other.rewrite_relative_import_extensions {
            return false;
        }
        if self.react_namespace != other.react_namespace {
            return false;
        }
        if self.root_dir != other.root_dir {
            return false;
        }
        if self.root_dirs != other.root_dirs {
            return false;
        }
        if self.skip_lib_check != other.skip_lib_check {
            return false;
        }
        if self.stable_type_ordering != other.stable_type_ordering {
            return false;
        }
        if self.strict != other.strict {
            return false;
        }
        if self.strict_bind_call_apply != other.strict_bind_call_apply {
            return false;
        }
        if self.strict_builtin_iterator_return != other.strict_builtin_iterator_return {
            return false;
        }
        if self.strict_function_types != other.strict_function_types {
            return false;
        }
        if self.strict_null_checks != other.strict_null_checks {
            return false;
        }
        if self.strict_property_initialization != other.strict_property_initialization {
            return false;
        }
        if self.strip_internal != other.strip_internal {
            return false;
        }
        if self.skip_default_lib_check != other.skip_default_lib_check {
            return false;
        }
        if self.source_map != other.source_map {
            return false;
        }
        if self.source_root != other.source_root {
            return false;
        }
        if self.suppress_output_path_check != other.suppress_output_path_check {
            return false;
        }
        if self.target != other.target {
            return false;
        }
        if self.trace_resolution != other.trace_resolution {
            return false;
        }
        if self.ts_build_info_file != other.ts_build_info_file {
            return false;
        }
        if self.type_roots != other.type_roots {
            return false;
        }
        if self.types != other.types {
            return false;
        }
        if self.use_define_for_class_fields != other.use_define_for_class_fields {
            return false;
        }
        if self.use_unknown_in_catch_variables != other.use_unknown_in_catch_variables {
            return false;
        }
        if self.verbatim_module_syntax != other.verbatim_module_syntax {
            return false;
        }
        if self.max_node_module_js_depth != other.max_node_module_js_depth {
            return false;
        }
        if self.allow_synthetic_default_imports != other.allow_synthetic_default_imports {
            return false;
        }
        if self.always_strict != other.always_strict {
            return false;
        }
        if self.base_url != other.base_url {
            return false;
        }
        if self.downlevel_iteration != other.downlevel_iteration {
            return false;
        }
        if self.es_module_interop != other.es_module_interop {
            return false;
        }
        if self.out_file != other.out_file {
            return false;
        }
        if self.config_file_path != other.config_file_path {
            return false;
        }
        if self.no_dts_resolution != other.no_dts_resolution {
            return false;
        }
        if self.paths_base_path != other.paths_base_path {
            return false;
        }
        if self.diagnostics != other.diagnostics {
            return false;
        }
        if self.extended_diagnostics != other.extended_diagnostics {
            return false;
        }
        if self.generate_cpu_profile != other.generate_cpu_profile {
            return false;
        }
        if self.generate_trace != other.generate_trace {
            return false;
        }
        if self.list_emitted_files != other.list_emitted_files {
            return false;
        }
        if self.list_files != other.list_files {
            return false;
        }
        if self.explain_files != other.explain_files {
            return false;
        }
        if self.list_files_only != other.list_files_only {
            return false;
        }
        if self.no_emit_for_js_files != other.no_emit_for_js_files {
            return false;
        }
        if self.preserve_watch_output != other.preserve_watch_output {
            return false;
        }
        if self.pretty != other.pretty {
            return false;
        }
        if self.version != other.version {
            return false;
        }
        if self.watch != other.watch {
            return false;
        }
        if self.show_config != other.show_config {
            return false;
        }
        if self.build != other.build {
            return false;
        }
        if self.help != other.help {
            return false;
        }
        if self.all != other.all {
            return false;
        }
        if self.run_external_code != other.run_external_code {
            return false;
        }
        if self.pprof_dir != other.pprof_dir {
            return false;
        }
        if self.single_threaded != other.single_threaded {
            return false;
        }
        if self.quiet != other.quiet {
            return false;
        }
        if self.checkers != other.checkers {
            return false;
        }
        true
    }
}

/// Go: `type ModuleDetectionKind int32` (tsc/internal/core/options_generated.go).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum ModuleDetectionKind {
    #[default]
    None = 0,
    Auto = 1,
    Legacy = 2,
    Force = 3,
}

impl ModuleDetectionKind {
    pub fn from_i32(value: i32) -> Option<ModuleDetectionKind> {
        match value {
            0 => Some(ModuleDetectionKind::None),
            1 => Some(ModuleDetectionKind::Auto),
            2 => Some(ModuleDetectionKind::Legacy),
            3 => Some(ModuleDetectionKind::Force),
            _ => None,
        }
    }
}

/// Go: `type ModuleKind int32` (tsc/internal/core/options_generated.go).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum ModuleKind {
    #[default]
    None = 0,
    CommonJS = 1,
    /// Deprecated: Do not use outside of options parsing and validation.
    AMD = 2,
    /// Deprecated: Do not use outside of options parsing and validation.
    UMD = 3,
    /// Deprecated: Do not use outside of options parsing and validation.
    System = 4,
    /// NOTE: ES module kinds should be contiguous to more easily check whether a module kind is *any* ES module kind.
    /// Non-ES module kinds should not come between ES2015 (the earliest ES module kind) and ESNext (the last ES
    /// module kind).
    ES2015 = 5,
    ES2020 = 6,
    ES2022 = 7,
    ESNext = 99,
    /// Node16+ is an amalgam of commonjs (albeit updated) and es2022+, and represents a distinct module system from es2020/esnext
    Node16 = 100,
    Node18 = 101,
    Node20 = 102,
    NodeNext = 199,
    Preserve = 200, // Emit as written
}

impl ModuleKind {
    pub fn from_i32(value: i32) -> Option<ModuleKind> {
        match value {
            0 => Some(ModuleKind::None),
            1 => Some(ModuleKind::CommonJS),
            2 => Some(ModuleKind::AMD),
            3 => Some(ModuleKind::UMD),
            4 => Some(ModuleKind::System),
            5 => Some(ModuleKind::ES2015),
            6 => Some(ModuleKind::ES2020),
            7 => Some(ModuleKind::ES2022),
            99 => Some(ModuleKind::ESNext),
            100 => Some(ModuleKind::Node16),
            101 => Some(ModuleKind::Node18),
            102 => Some(ModuleKind::Node20),
            199 => Some(ModuleKind::NodeNext),
            200 => Some(ModuleKind::Preserve),
            _ => None,
        }
    }
}

/// Go: `type ModuleResolutionKind int32` (tsc/internal/core/options_generated.go).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum ModuleResolutionKind {
    #[default]
    Unknown = 0,
    /// Deprecated: Do not use outside of options parsing and validation.
    Classic = 1,
    /// Deprecated: Do not use outside of options parsing and validation.
    Node10 = 2,
    /// Starting with node16, node's module resolver has significant departures from traditional cjs resolution
    /// to better support ECMAScript modules and their use within node - however more features are still being added.
    /// TypeScript's Node ESM support was introduced after Node 12 went end-of-life, and Node 14 is the earliest stable
    /// version that supports both pattern trailers - *but*, Node 16 is the first version that also supports ECMAScript 2022.
    /// In turn, we offer both a `NodeNext` moving resolution target, and a `Node16` version-anchored resolution target
    Node16 = 3,
    NodeNext = 99, // Not simply `Node16` so that compiled code linked against TS can use the `Next` value reliably (same as with `ModuleKind`)
    Bundler = 100,
}

impl ModuleResolutionKind {
    pub fn from_i32(value: i32) -> Option<ModuleResolutionKind> {
        match value {
            0 => Some(ModuleResolutionKind::Unknown),
            1 => Some(ModuleResolutionKind::Classic),
            2 => Some(ModuleResolutionKind::Node10),
            3 => Some(ModuleResolutionKind::Node16),
            99 => Some(ModuleResolutionKind::NodeNext),
            100 => Some(ModuleResolutionKind::Bundler),
            _ => None,
        }
    }
}

/// Go: `type NewLineKind int32` (tsc/internal/core/options_generated.go).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum NewLineKind {
    #[default]
    None = 0,
    CRLF = 1,
    LF = 2,
}

impl NewLineKind {
    pub fn from_i32(value: i32) -> Option<NewLineKind> {
        match value {
            0 => Some(NewLineKind::None),
            1 => Some(NewLineKind::CRLF),
            2 => Some(NewLineKind::LF),
            _ => None,
        }
    }
}

/// Go: `type ScriptTarget int32` (tsc/internal/core/options_generated.go).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum ScriptTarget {
    #[default]
    None = 0,
    /// Deprecated: Do not use outside of options parsing and validation.
    ES5 = 1,
    ES2015 = 2,
    ES2016 = 3,
    ES2017 = 4,
    ES2018 = 5,
    ES2019 = 6,
    ES2020 = 7,
    ES2021 = 8,
    ES2022 = 9,
    ES2023 = 10,
    ES2024 = 11,
    ES2025 = 12,
    ES2026 = 13,
    ESNext = 99,
    JSON = 100,
}

impl ScriptTarget {
    pub fn from_i32(value: i32) -> Option<ScriptTarget> {
        match value {
            0 => Some(ScriptTarget::None),
            1 => Some(ScriptTarget::ES5),
            2 => Some(ScriptTarget::ES2015),
            3 => Some(ScriptTarget::ES2016),
            4 => Some(ScriptTarget::ES2017),
            5 => Some(ScriptTarget::ES2018),
            6 => Some(ScriptTarget::ES2019),
            7 => Some(ScriptTarget::ES2020),
            8 => Some(ScriptTarget::ES2021),
            9 => Some(ScriptTarget::ES2022),
            10 => Some(ScriptTarget::ES2023),
            11 => Some(ScriptTarget::ES2024),
            12 => Some(ScriptTarget::ES2025),
            13 => Some(ScriptTarget::ES2026),
            99 => Some(ScriptTarget::ESNext),
            100 => Some(ScriptTarget::JSON),
            _ => None,
        }
    }

    /// Go: `ScriptTargetLatest ScriptTarget = ScriptTargetESNext` (value alias).
    #[allow(non_upper_case_globals)] // Go-parity name
    pub const Latest: ScriptTarget = ScriptTarget::ESNext;

    /// Go: `ScriptTargetLatestStandard ScriptTarget = ScriptTargetES2026` (value alias).
    #[allow(non_upper_case_globals)] // Go-parity name
    pub const LatestStandard: ScriptTarget = ScriptTarget::ES2026;
}

/// Go: `type JsxEmit int32` (tsc/internal/core/options_generated.go).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(i32)]
pub enum JsxEmit {
    #[default]
    None = 0,
    Preserve = 1,
    React = 2,
    ReactNative = 3,
    ReactJSX = 4,
    ReactJSXDev = 5,
}

impl JsxEmit {
    pub fn from_i32(value: i32) -> Option<JsxEmit> {
        match value {
            0 => Some(JsxEmit::None),
            1 => Some(JsxEmit::Preserve),
            2 => Some(JsxEmit::React),
            3 => Some(JsxEmit::ReactNative),
            4 => Some(JsxEmit::ReactJSX),
            5 => Some(JsxEmit::ReactJSXDev),
            _ => None,
        }
    }
}

/// Go: `var ModuleKindToModuleResolutionKind = map[ModuleKind]ModuleResolutionKind{...}`.
/// A missing key in Go yields the zero value; the port returns `None` for
/// kinds with no entry.
pub fn module_kind_to_module_resolution_kind(
    module_kind: ModuleKind,
) -> Option<ModuleResolutionKind> {
    match module_kind {
        ModuleKind::Node16 => Some(ModuleResolutionKind::Node16),
        ModuleKind::NodeNext => Some(ModuleResolutionKind::NodeNext),
        _ => None,
    }
}

// Go: `func (value ModuleResolutionKind) String() string` — panics on the zero value
// (and, in Go, on out-of-range ints; impossible on the closed Rust enum).
impl fmt::Display for ModuleResolutionKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ModuleResolutionKind::Unknown => {
                panic!("should not use zero value of ModuleResolutionKind")
            }
            ModuleResolutionKind::Classic => f.write_str("Classic"),
            ModuleResolutionKind::Node10 => f.write_str("Node10"),
            ModuleResolutionKind::Node16 => f.write_str("Node16"),
            ModuleResolutionKind::NodeNext => f.write_str("NodeNext"),
            ModuleResolutionKind::Bundler => f.write_str("Bundler"),
        }
    }
}

// Go: `func (value JsxEmit) String() string` — panics on the zero value
// (and, in Go, on out-of-range ints; impossible on the closed Rust enum).
impl fmt::Display for JsxEmit {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            JsxEmit::None => panic!("should not use zero value of JsxEmit"),
            JsxEmit::Preserve => f.write_str("preserve"),
            JsxEmit::React => f.write_str("react"),
            JsxEmit::ReactNative => f.write_str("react-native"),
            JsxEmit::ReactJSX => f.write_str("react-jsx"),
            JsxEmit::ReactJSXDev => f.write_str("react-jsxdev"),
        }
    }
}

/// Go: `type TypeAcquisition struct`.
#[derive(Clone, Debug, Default)]
pub struct TypeAcquisition {
    pub enable: Tristate,
    pub include: Vec<String>,
    pub exclude: Vec<String>,
    pub disable_filename_based_type_acquisition: Tristate,
}

/// Go: `type BuildOptions struct`.
#[derive(Clone, Debug, Default)]
pub struct BuildOptions {
    pub dry: Tristate,
    pub force: Tristate,
    pub verbose: Tristate,
    pub builders: Option<i64>,
    pub stop_build_on_errors: Tristate,

    // Internal fields
    pub clean: Tristate,
}

#[cfg(test)]
mod options_generated_test {
    // Parity spot-checks against tsc/internal/core/options_generated.go
    // @ ec47d33c23e464a17cdf2475632cba629bee8763 — baseline reference only. Per SPEC §6 the Go output is
    // never a generation input; these assertions pin the Rust mirror to it
    // (same role as GO-BASELINE.txt for the gen-ast ordinal table).

    use super::*;

    #[test]
    fn module_detection_kind_matches_go_baseline() {
        // Baseline (options_generated.go): None=0, Auto=1, Legacy=2, Force=3.
        let values = [
            (ModuleDetectionKind::None, 0i32),
            (ModuleDetectionKind::Auto, 1i32),
            (ModuleDetectionKind::Legacy, 2i32),
            (ModuleDetectionKind::Force, 3i32),
        ];
        for (member, value) in values {
            assert_eq!(member as i32, value);
            assert_eq!(ModuleDetectionKind::from_i32(value), Some(member));
        }
        assert_eq!(values.len(), 4);
        assert_eq!(ModuleDetectionKind::from_i32(4), None);
    }

    #[test]
    fn module_kind_matches_go_baseline() {
        // Baseline (options_generated.go): None=0, CommonJS=1, AMD=2, UMD=3, System=4, ES2015=5, ES2020=6, ES2022=7, ESNext=99, Node16=100, Node18=101, Node20=102, NodeNext=199, Preserve=200.
        let values = [
            (ModuleKind::None, 0i32),
            (ModuleKind::CommonJS, 1i32),
            (ModuleKind::AMD, 2i32),
            (ModuleKind::UMD, 3i32),
            (ModuleKind::System, 4i32),
            (ModuleKind::ES2015, 5i32),
            (ModuleKind::ES2020, 6i32),
            (ModuleKind::ES2022, 7i32),
            (ModuleKind::ESNext, 99i32),
            (ModuleKind::Node16, 100i32),
            (ModuleKind::Node18, 101i32),
            (ModuleKind::Node20, 102i32),
            (ModuleKind::NodeNext, 199i32),
            (ModuleKind::Preserve, 200i32),
        ];
        for (member, value) in values {
            assert_eq!(member as i32, value);
            assert_eq!(ModuleKind::from_i32(value), Some(member));
        }
        assert_eq!(values.len(), 14);
        assert_eq!(ModuleKind::from_i32(201), None);
    }

    #[test]
    fn module_resolution_kind_matches_go_baseline() {
        // Baseline (options_generated.go): Unknown=0, Classic=1, Node10=2, Node16=3, NodeNext=99, Bundler=100.
        let values = [
            (ModuleResolutionKind::Unknown, 0i32),
            (ModuleResolutionKind::Classic, 1i32),
            (ModuleResolutionKind::Node10, 2i32),
            (ModuleResolutionKind::Node16, 3i32),
            (ModuleResolutionKind::NodeNext, 99i32),
            (ModuleResolutionKind::Bundler, 100i32),
        ];
        for (member, value) in values {
            assert_eq!(member as i32, value);
            assert_eq!(ModuleResolutionKind::from_i32(value), Some(member));
        }
        assert_eq!(values.len(), 6);
        assert_eq!(ModuleResolutionKind::from_i32(101), None);
    }

    #[test]
    fn new_line_kind_matches_go_baseline() {
        // Baseline (options_generated.go): None=0, CRLF=1, LF=2.
        let values = [
            (NewLineKind::None, 0i32),
            (NewLineKind::CRLF, 1i32),
            (NewLineKind::LF, 2i32),
        ];
        for (member, value) in values {
            assert_eq!(member as i32, value);
            assert_eq!(NewLineKind::from_i32(value), Some(member));
        }
        assert_eq!(values.len(), 3);
        assert_eq!(NewLineKind::from_i32(3), None);
    }

    #[test]
    fn script_target_matches_go_baseline() {
        // Baseline (options_generated.go): None=0, ES5=1, ES2015=2, ES2016=3, ES2017=4, ES2018=5, ES2019=6, ES2020=7, ES2021=8, ES2022=9, ES2023=10, ES2024=11, ES2025=12, ES2026=13, ESNext=99, JSON=100.
        let values = [
            (ScriptTarget::None, 0i32),
            (ScriptTarget::ES5, 1i32),
            (ScriptTarget::ES2015, 2i32),
            (ScriptTarget::ES2016, 3i32),
            (ScriptTarget::ES2017, 4i32),
            (ScriptTarget::ES2018, 5i32),
            (ScriptTarget::ES2019, 6i32),
            (ScriptTarget::ES2020, 7i32),
            (ScriptTarget::ES2021, 8i32),
            (ScriptTarget::ES2022, 9i32),
            (ScriptTarget::ES2023, 10i32),
            (ScriptTarget::ES2024, 11i32),
            (ScriptTarget::ES2025, 12i32),
            (ScriptTarget::ES2026, 13i32),
            (ScriptTarget::ESNext, 99i32),
            (ScriptTarget::JSON, 100i32),
        ];
        for (member, value) in values {
            assert_eq!(member as i32, value);
            assert_eq!(ScriptTarget::from_i32(value), Some(member));
        }
        assert_eq!(values.len(), 16);
        assert_eq!(ScriptTarget::from_i32(101), None);
        assert_eq!(ScriptTarget::Latest, ScriptTarget::ESNext);
        assert_eq!(ScriptTarget::LatestStandard, ScriptTarget::ES2026);
    }

    #[test]
    fn jsx_emit_matches_go_baseline() {
        // Baseline (options_generated.go): None=0, Preserve=1, React=2, ReactNative=3, ReactJSX=4, ReactJSXDev=5.
        let values = [
            (JsxEmit::None, 0i32),
            (JsxEmit::Preserve, 1i32),
            (JsxEmit::React, 2i32),
            (JsxEmit::ReactNative, 3i32),
            (JsxEmit::ReactJSX, 4i32),
            (JsxEmit::ReactJSXDev, 5i32),
        ];
        for (member, value) in values {
            assert_eq!(member as i32, value);
            assert_eq!(JsxEmit::from_i32(value), Some(member));
        }
        assert_eq!(values.len(), 6);
        assert_eq!(JsxEmit::from_i32(6), None);
    }

    #[test]
    fn stringer_outputs_match_go() {
        // Baseline: ModuleResolutionKind.String() and JsxEmit.String() in
        // options_generated.go.
        assert_eq!(ModuleResolutionKind::Node10.to_string(), "Node10");
        assert_eq!(ModuleResolutionKind::Node16.to_string(), "Node16");
        assert_eq!(ModuleResolutionKind::NodeNext.to_string(), "NodeNext");
        assert_eq!(ModuleResolutionKind::Bundler.to_string(), "Bundler");
        assert_eq!(ModuleResolutionKind::Classic.to_string(), "Classic");
        assert_eq!(JsxEmit::Preserve.to_string(), "preserve");
        assert_eq!(JsxEmit::React.to_string(), "react");
        assert_eq!(JsxEmit::ReactNative.to_string(), "react-native");
        assert_eq!(JsxEmit::ReactJSX.to_string(), "react-jsx");
        assert_eq!(JsxEmit::ReactJSXDev.to_string(), "react-jsxdev");
    }

    #[test]
    #[should_panic(expected = "should not use zero value of ModuleResolutionKind")]
    fn module_resolution_kind_zero_display_panics_like_go() {
        let _ = ModuleResolutionKind::Unknown.to_string();
    }

    #[test]
    #[should_panic(expected = "should not use zero value of JsxEmit")]
    fn jsx_emit_zero_display_panics_like_go() {
        let _ = JsxEmit::None.to_string();
    }

    #[test]
    fn module_kind_to_module_resolution_kind_matches_go() {
        // Baseline: the Go map has exactly two entries.
        assert_eq!(
            module_kind_to_module_resolution_kind(ModuleKind::Node16),
            Some(ModuleResolutionKind::Node16)
        );
        assert_eq!(
            module_kind_to_module_resolution_kind(ModuleKind::NodeNext),
            Some(ModuleResolutionKind::NodeNext)
        );
        assert_eq!(
            module_kind_to_module_resolution_kind(ModuleKind::ESNext),
            None
        );
    }

    #[test]
    fn clone_and_equals_match_go() {
        // Baseline: the generated Clone/Equals in options_generated.go —
        // clones are value-equal; any differing field breaks Equals.
        let options = CompilerOptions {
            allow_js: Tristate::TSTrue,
            target: ScriptTarget::ES2020,
            lib: vec!["lib.es2015.d.ts".to_string()],
            max_node_module_js_depth: Some(2),
            ..CompilerOptions::default()
        };

        let clone = options.clone();
        assert!(options.equals(&clone));
        assert!(clone.equals(&options));

        let mut other = clone.clone();
        other.strict = Tristate::TSTrue;
        assert!(!options.equals(&other));

        let mut other = clone.clone();
        other.max_node_module_js_depth = None;
        assert!(!options.equals(&other));

        let mut other = clone.clone();
        other.lib = Vec::new();
        assert!(!options.equals(&other));

        let mut other = clone.clone();
        let mut paths = OrderedMap::new();
        paths.set("*".to_string(), vec!["out/*".to_string()]);
        other.paths = Some(paths);
        assert!(!options.equals(&other));

        let mut same = clone.clone();
        let mut paths = OrderedMap::new();
        paths.set("*".to_string(), vec!["out/*".to_string()]);
        same.paths = other.paths.clone();
        assert!(other.equals(&same));

        assert!(CompilerOptions::default().equals(&CompilerOptions::default()));
    }
}
