// Code generated by "stringer -type=ScriptKind -output=scriptkind_stringer_generated.go"; DO NOT EDIT.
// PORT: generated Rust checked in; rust/tools/gen-options is TODO(gen).
// Ported from tsc/internal/core/scriptkind_stringer_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763

use crate::scriptkind::ScriptKind;
use std::fmt;

const SCRIPT_KIND_NAME_0: &str =
    "ScriptKindUnknownScriptKindJSScriptKindJSXScriptKindTSScriptKindTSX";
const SCRIPT_KIND_NAME_1: &str = "ScriptKindJSON";

const SCRIPT_KIND_INDEX_0: [u8; 6] = [0, 17, 29, 42, 54, 67];

impl fmt::Display for ScriptKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // PORT: Rust enums cannot hold out-of-range ordinals (including the
        // reserved 5 and 7), so the `ScriptKind(N)` fallback from the Go
        // stringer is unreachable.
        match self {
            ScriptKind::Json => f.write_str(SCRIPT_KIND_NAME_1),
            _ => {
                let i = *self as usize;
                f.write_str(
                    &SCRIPT_KIND_NAME_0
                        [SCRIPT_KIND_INDEX_0[i] as usize..SCRIPT_KIND_INDEX_0[i + 1] as usize],
                )
            }
        }
    }
}
