// Ported from tsc/internal/core/scriptkind_stringer_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763
//
// Code generated by "stringer -type=ScriptKind -output=scriptkind_stringer_generated.go"; DO NOT EDIT.
// PORT: Go's stringer string-slicing tables are replaced by a Display impl
// with identical strings. Out-of-range values print as `ScriptKind(<n>)`,
// matching the stringer default — use `ScriptKind::from_i32` for invalid
// discriminants.

use std::fmt;

use crate::scriptkind::ScriptKind;

impl fmt::Display for ScriptKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ScriptKind::Unknown => f.write_str("ScriptKindUnknown"),
            ScriptKind::JS => f.write_str("ScriptKindJS"),
            ScriptKind::JSX => f.write_str("ScriptKindJSX"),
            ScriptKind::TS => f.write_str("ScriptKindTS"),
            ScriptKind::TSX => f.write_str("ScriptKindTSX"),
            ScriptKind::JSON => f.write_str("ScriptKindJSON"),
        }
    }
}

/// Formats a raw discriminant exactly like the Go stringer, including the
/// `ScriptKind(<n>)` fallback for reserved/unknown values.
pub fn script_kind_string(i: i32) -> String {
    match ScriptKind::from_i32(i) {
        Some(kind) => kind.to_string(),
        None => format!("ScriptKind({i})"),
    }
}
