// Code generated by "stringer -type=ScriptTarget -trimprefix=ScriptTarget -output=scripttarget_stringer_generated.go"; DO NOT EDIT.
// PORT: generated Rust checked in; rust/tools/gen-options is TODO(gen).
// Ported from tsc/internal/core/scripttarget_stringer_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763

use crate::options_generated::ScriptTarget;
use std::fmt;

const SCRIPT_TARGET_NAME_0: &str =
    "NoneES5ES2015ES2016ES2017ES2018ES2019ES2020ES2021ES2022ES2023ES2024ES2025ES2026";
const SCRIPT_TARGET_NAME_1: &str = "ESNextJSON";

const SCRIPT_TARGET_INDEX_0: [u8; 15] =
    [0, 4, 7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79];
const SCRIPT_TARGET_INDEX_1: [u8; 3] = [0, 6, 10];

impl fmt::Display for ScriptTarget {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // PORT: Rust enums cannot hold out-of-range ordinals, so the
        // `ScriptTarget(N)` fallback from the Go stringer is unreachable.
        let i = *self as i32;
        if (0..=13).contains(&i) {
            let i = i as usize;
            return f.write_str(
                &SCRIPT_TARGET_NAME_0
                    [SCRIPT_TARGET_INDEX_0[i] as usize..SCRIPT_TARGET_INDEX_0[i + 1] as usize],
            );
        }
        let i = (i - 99) as usize;
        f.write_str(
            &SCRIPT_TARGET_NAME_1
                [SCRIPT_TARGET_INDEX_1[i] as usize..SCRIPT_TARGET_INDEX_1[i + 1] as usize],
        )
    }
}
