// Ported from tsc/internal/core/tristate_stringer_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763
//
// Code generated by "stringer -type=Tristate -output=tristate_stringer_generated.go"; DO NOT EDIT.
// PORT: Go's stringer string-slicing tables are replaced by a Display impl
// with identical strings.

use std::fmt;

use crate::tristate::Tristate;

impl fmt::Display for Tristate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Tristate::TSUnknown => f.write_str("TSUnknown"),
            Tristate::TSFalse => f.write_str("TSFalse"),
            Tristate::TSTrue => f.write_str("TSTrue"),
        }
    }
}
