// Code generated by "stringer -type=Tristate -output=tristate_stringer_generated.go -trimprefix=Tristate". DO NOT EDIT.
// PORT: generated Rust checked in; rust/tools/gen-options is TODO(gen).
// Ported from tsc/internal/core/tristate_stringer_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763

use crate::tristate::Tristate;
use std::fmt;

const TRISTATE_NAME: &str = "TSUnknownTSFalseTSTrue";

const TRISTATE_INDEX: [u8; 4] = [0, 9, 16, 22];

impl fmt::Display for Tristate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // PORT: Rust enums cannot hold out-of-range ordinals, so the
        // `Tristate(-N)` fallback from the Go stringer is unreachable.
        let i = *self as usize;
        f.write_str(&TRISTATE_NAME[TRISTATE_INDEX[i] as usize..TRISTATE_INDEX[i + 1] as usize])
    }
}
