// Code generator for the embedded lib table — the Rust analogue of
// tsc/internal/bundled/generate.go + `//go:embed` in embed_generated.go.
// Scans the `libs` symlink (→ tsc/internal/bundled/libs) and emits
// `libs_generated.rs` into OUT_DIR with `include_str!` entries.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let libs_dir = Path::new(&manifest).join("libs");
    println!("cargo:rerun-if-changed={}", libs_dir.display());

    let mut names: Vec<String> = fs::read_dir(&libs_dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".d.ts"))
        .collect();
    names.sort();

    let mut out = String::from(
        "// Code generated by build.rs; DO NOT EDIT.\n\
         // Mirrors tsc/internal/bundled/libs_generated.go + embed_generated.go.\n\n\
         /// `LibNames` — all bundled lib files, sorted by name.\n\
         /// (For the list sorted by load order, see tsoptions.Libs.)\n\
         pub static LIB_NAMES: &[&str] = &[\n",
    );
    for name in &names {
        out.push_str(&format!("    {name:?},\n"));
    }
    out.push_str(
        "];\n\n\
         /// `embeddedContents` — path within `bundled:///`, e.g. \"libs/lib.d.ts\",\n\
         /// to file contents. Sorted by key so lookups can binary-search.\n\
         pub(crate) static EMBEDDED_CONTENTS: &[(&str, &str)] = &[\n",
    );
    for name in &names {
        out.push_str(&format!(
            "    (\"libs/{name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/libs/{name}\"))),\n",
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("libs_generated.rs");
    fs::write(&dest, out).unwrap();
}
