// Ported from tsc/internal/diagnostics/diagnostics_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763
//
// The Go file is `// Code generated by generate.go; DO NOT EDIT.` — in Rust
// the equivalent table is emitted by this crate's `build.rs` into OUT_DIR
// (SPEC §5.8) and included here.

use crate::{Category, Key, Message};

include!(concat!(env!("OUT_DIR"), "/messages_generated.rs"));

// Aliases kept from the pre-codegen stub so early dependents keep compiling.
// These point at the same `Message` statics under their Go-generated names.
pub use self::Cannot_find_name_0 as CANNOT_FIND_NAME_0;
pub use self::X_0_is_declared_here as X_0_IS_DECLARED_HERE;
pub use self::X_resolution_mode_should_be_either_require_or_import as X_RESOLUTION_MODE_SHOULD_BE_EITHER_REQUIRE_OR_IMPORT;
