// Ported from tsc/internal/diagnostics/loc_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763
//
// The Go file is `// Code generated by generate.go; DO NOT EDIT.` and embeds
// one `loc/<tag>.json.gz` per locale via `//go:embed`, lazily gunzipping +
// JSON-parsing each on first use (`sync.OnceValue`). The Rust `build.rs`
// emits the same per-locale lazy structure into OUT_DIR — but as sorted
// `&[(&str, &str)]` statics behind `OnceLock` maps, so no gzip or runtime
// JSON parse is needed.
//
// `matcher`/`localeFuncs` are generated alongside; the simplified exact-tag
// match lives in `diagnostics.rs::get_localized_messages` (PORT note there).

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::Key;

type LocaleLoader = fn() -> &'static HashMap<Key, String>;

include!(concat!(env!("OUT_DIR"), "/loc_generated.rs"));
