// Ported from tsc/internal/diagnostics/stringer_generated.go @ ec47d33c23e464a17cdf2475632cba629bee8763
// (in Go: `// Code generated by "stringer -type=Category -output=stringer_generated.go"; DO NOT EDIT.`)

use std::fmt;

use crate::Category;

const CATEGORY_NAME: &str = "CategoryWarningCategoryErrorCategorySuggestionCategoryMessage";

const CATEGORY_INDEX: [u8; 5] = [0, 15, 28, 46, 61];

/// `func (i Category) String() string`
///
/// PORT: `Category` is a Rust enum, so the Go stringer's out-of-range branch
/// (`"Category(" + strconv.FormatInt(...) + ")"`) is unreachable — the
/// discriminant is always 0..=3.
impl fmt::Display for Category {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let idx = *self as usize;
        f.write_str(&CATEGORY_NAME[CATEGORY_INDEX[idx] as usize..CATEGORY_INDEX[idx + 1] as usize])
    }
}
