// Codegen for tsc-diagnostics — replaces the Go generator
// (`tsc/internal/diagnostics/generate.go`, `//go:build ignore`) per SPEC §5.8:
// `diagnostics/diagnostics_generated.go` ← `diagnosticMessages.json` via
// `build.rs` (single source of truth — the JSON is NOT forked).
// `generate_deps.go` (a blank gzip import for `go mod tidy`) has no Rust
// analogue; this script emits `messages_generated.rs` + `loc_generated.rs`
// into OUT_DIR.
//
// Ported from tsc/internal/diagnostics/generate.go @ ec47d33c23e464a17cdf2475632cba629bee8763

use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

struct DiagnosticMessage {
    category: String,
    code: i64,
    reports_unnecessary: bool,
    reports_deprecated: bool,
    // spelling error here is [sic] in Strada
    elided_in_compatibility_pyramid: bool,
    key: String, // the JSON property name — the English message text
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let repo_root = manifest_dir
        .join("../../..")
        .canonicalize()
        .expect("failed to resolve repo root from CARGO_MANIFEST_DIR");
    let diagnostics_dir = repo_root.join("tsc/internal/diagnostics");
    let loc_dir = diagnostics_dir.join("loc");
    let project_path = repo_root.join("tools/LocProject.json");
    let messages_path = diagnostics_dir.join("diagnosticMessages.json");

    println!("cargo:rerun-if-changed={}", messages_path.display());
    println!("cargo:rerun-if-changed={}", project_path.display());
    println!("cargo:rerun-if-changed={}", loc_dir.display());

    let diagnostic_messages = read_raw_messages(&messages_path);
    // Collect known keys for filtering localizations.
    let mut known_keys = BTreeSet::new();
    for m in &diagnostic_messages {
        let (_, key) = convert_property_name(&m.key, m.code);
        known_keys.insert(key);
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let diagnostics_out = generate_diagnostics(&diagnostic_messages);
    fs::write(out_dir.join("messages_generated.rs"), diagnostics_out)
        .expect("failed to write messages_generated.rs");

    // Generate localizations file
    let locale_names = read_locale_names(&project_path, &loc_dir);
    let loc_out = generate_localizations(&known_keys, &loc_dir, &locale_names);
    fs::write(out_dir.join("loc_generated.rs"), loc_out).expect("failed to write loc_generated.rs");
}

// `readRawMessages`: decode diagnosticMessages.json (map of English text →
// metadata), fatal on duplicate codes, return sorted-by-code.
fn read_raw_messages(path: &Path) -> Vec<DiagnosticMessage> {
    let file = fs::read_to_string(path).expect("failed to open diagnosticMessages.json");
    let raw: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(&file).expect("failed to decode diagnosticMessages.json");

    let mut code_to_message: BTreeMap<i64, DiagnosticMessage> = BTreeMap::new();
    for (k, v) in &raw {
        let code = v["code"].as_i64().expect("diagnostic message missing code");
        let m = DiagnosticMessage {
            category: v["category"]
                .as_str()
                .expect("diagnostic message missing category")
                .to_string(),
            code,
            reports_unnecessary: v["reportsUnnecessary"].as_bool().unwrap_or(false),
            reports_deprecated: v["reportsDeprecated"].as_bool().unwrap_or(false),
            elided_in_compatibility_pyramid: v["elidedInCompatabilityPyramid"]
                .as_bool()
                .unwrap_or(false),
            key: k.clone(),
        };
        if let Some(existing) = code_to_message.get(&m.code) {
            panic!(
                "diagnostics {:?} and {:?} both use code {}",
                existing.key, k, m.code
            );
        }
        code_to_message.insert(m.code, m);
    }
    // BTreeMap<i64, _> iterates in code order — same as Go's SortFunc by Code.
    code_to_message.into_values().collect()
}

fn generate_diagnostics(diagnostic_messages: &[DiagnosticMessage]) -> String {
    let mut buf = String::from(
        "// Code generated by rust/crates/diagnostics/build.rs from\n\
         // tsc/internal/diagnostics/diagnosticMessages.json; DO NOT EDIT.\n\n",
    );

    for m in diagnostic_messages {
        let (var_name, key) = convert_property_name(&m.key, m.code);
        let category = match m.category.as_str() {
            "Warning" => "Warning",
            "Error" => "Error",
            "Suggestion" => "Suggestion",
            "Message" => "Message",
            other => panic!("unknown diagnostic category {other:?}"),
        };
        writeln!(buf, "#[allow(non_upper_case_globals)]").unwrap();
        writeln!(
            buf,
            "pub static {var_name}: Message = Message {{ code: {code}, category: Category::{category}, key: {key:?}, text: {text:?}, reports_unnecessary: {ru}, elided_in_compatibility_pyramid: {eicp}, reports_deprecated: {rd} }};\n",
            code = m.code,
            text = m.key,
            ru = m.reports_unnecessary,
            eicp = m.elided_in_compatibility_pyramid,
            rd = m.reports_deprecated,
        )
        .unwrap();
    }

    // Addresses can be statically initialized even across package initialization calls.
    // Copying the pointer variables or using a large map literal generates substantial initialization code.
    buf.push_str("/// Go: `var allMessages = [...]**Message`.\n");
    buf.push_str("pub static ALL_MESSAGES: &[&Message] = &[\n");
    for m in diagnostic_messages {
        let (var_name, _) = convert_property_name(&m.key, m.code);
        writeln!(buf, "    &{var_name},").unwrap();
    }
    buf.push_str("];\n");

    buf
}

// `readLocaleNames`: find the LocItem for the diagnostics source file in
// tools/LocProject.json, take its declared `Languages` list in order, and
// validate it against the `loc/*.generated.json` files on disk.
//
// PORT: Go resolves both paths to absolute form before comparing
// (`filepath.Join(projectRoot, itemSourceFile) == sourcePath`); both sides are
// fixed repo-relative paths here, so we compare the normalized relative path.
fn read_locale_names(project_path: &Path, locale_dir: &Path) -> Vec<String> {
    let file = fs::read_to_string(project_path).expect("failed to open localization project");
    let project: serde_json::Value =
        serde_json::from_str(&file).expect("failed to decode localization project");

    const SOURCE_REL: &str = "tsc/internal/diagnostics/diagnosticMessages.generated.json";
    let mut languages_value: Option<String> = None;
    for proj in project["Projects"].as_array().into_iter().flatten() {
        for item in proj["LocItems"].as_array().into_iter().flatten() {
            // filepath.FromSlash(strings.ReplaceAll(item.SourceFile, "\\", "/"))
            let item_source_file = item["SourceFile"]
                .as_str()
                .expect("LocItem missing SourceFile")
                .replace('\\', "/");
            if item_source_file != SOURCE_REL {
                continue;
            }
            if languages_value.is_some() {
                panic!(
                    "duplicate localization item for {SOURCE_REL:?} in {}",
                    project_path.display()
                );
            }
            languages_value = Some(
                item["Languages"]
                    .as_str()
                    .expect("LocItem missing Languages")
                    .to_string(),
            );
        }
    }
    let languages_value = languages_value.unwrap_or_else(|| {
        panic!(
            "localization item for {SOURCE_REL:?} not found in {}",
            project_path.display()
        )
    });

    let languages: Vec<String> = languages_value.split(';').map(str::to_string).collect();
    // PORT: Go additionally validates each declared locale parses to its own
    // canonical BCP-47 form via language.Parse; our tsc-locale parse() is a
    // subset, so we just require non-empty.
    let mut declared: BTreeSet<String> = BTreeSet::new();
    for locale_name in &languages {
        if locale_name.is_empty() || !declared.insert(locale_name.clone()) {
            panic!(
                "invalid or duplicate locale {locale_name:?} in {}",
                project_path.display()
            );
        }
    }

    for entry in fs::read_dir(locale_dir).expect("failed to read locale directory") {
        let entry = entry.expect("failed to read locale directory entry");
        let name = entry
            .file_name()
            .into_string()
            .expect("non-UTF-8 locale filename");
        if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) || !name.ends_with(".json") {
            continue;
        }
        if !name.ends_with(".generated.json") {
            panic!("locale file {name:?} must use the .generated.json suffix");
        }
        let locale_name = name.trim_end_matches(".generated.json");
        if !declared.remove(locale_name) {
            panic!(
                "locale file {:?} is not declared in {}",
                locale_dir.join(&name),
                project_path.display()
            );
        }
    }
    if !declared.is_empty() {
        panic!(
            "locales declared in {} have no handback files: {}",
            project_path.display(),
            declared.into_iter().collect::<Vec<_>>().join(", ")
        );
    }

    languages
}

// `generateLocalizations`: for each declared locale (project order), read
// loc/<tag>.generated.json, drop keys not in `known_keys` (stale translations),
// and emit a sorted static table + `OnceLock` loader. Locales with no known
// translations are skipped — matching Go's `if len(localizedMessages) == 0 {
// continue }`.
//
// PORT: Go gzips each filtered table to loc/<tag>.json.gz, embeds it, and
// lazily gunzips+parses JSON at runtime. We emit a sorted `&[(&str, &str)]`
// static instead — no gzip dependency, same laziness via `OnceLock`.
fn generate_localizations(
    known_keys: &BTreeSet<String>,
    loc_dir: &Path,
    locale_names: &[String],
) -> String {
    let mut buf = String::from(
        "// Code generated by rust/crates/diagnostics/build.rs from\n\
         // tsc/internal/diagnostics/loc/*.generated.json; DO NOT EDIT.\n\n",
    );

    struct LocaleInfo {
        var_name: String,
        tgt_cul: String,
        entries: BTreeMap<String, String>,
    }

    let mut locales: Vec<LocaleInfo> = Vec::new();

    for tgt_cul in locale_names {
        let locale_file = loc_dir.join(format!("{tgt_cul}.generated.json"));
        let localized = read_localized_messages(&locale_file);

        // BTreeMap keeps the sorted order of Go's OrderedMap built from
        // slices.Sorted(maps.Keys(...)).
        let ordered: BTreeMap<String, String> = localized
            .into_iter()
            .filter(|(key, _)| known_keys.contains(key))
            .collect();
        if ordered.is_empty() {
            continue;
        }

        // Convert locale code to a valid Rust identifier (Go strips `-`/`_`
        // to get `zhCN`; the snake_case mirror is `zh_cn`).
        let locale_var = tgt_cul.to_lowercase().replace('-', "_");

        locales.push(LocaleInfo {
            var_name: locale_var,
            tgt_cul: tgt_cul.clone(),
            entries: ordered,
        });
    }

    // Generate matcher with inlined tags.
    // English is first (index 0) as the default/fallback with no translation needed.
    buf.push_str("/// Tags in matcher order — index 0 is English (the default/fallback,\n");
    buf.push_str("/// which has no translation table). Go: `language.NewMatcher`.\n");
    buf.push_str("pub(crate) static MATCHER_TAGS: &[&str] = &[\n    \"en\",\n");
    for loc in &locales {
        writeln!(buf, "    {:?},", loc.tgt_cul).unwrap();
    }
    buf.push_str("];\n");

    // Generate index-to-function map for matcher results.
    // English (index 0) returns None since we use the default English text.
    buf.push_str("\n/// Parallel to `MATCHER_TAGS`; index 0 is `None` for English.\n");
    buf.push_str("/// Go: `localeFuncs = []func() map[Key]string`.\n");
    buf.push_str("pub(crate) static LOCALE_FUNCS: &[Option<LocaleLoader>] = &[\n    None, // English (default)\n");
    for loc in &locales {
        writeln!(buf, "    Some({}),", loc.var_name).unwrap();
    }
    buf.push_str("];\n");

    // Generate helper building the runtime map from a static table.
    // Go: `loadLocaleData(data string)` (gunzip + json.UnmarshalRead).
    buf.push_str(
        "\nfn load_locale_data(data: &'static [(&'static str, &'static str)]) -> HashMap<Key, String> {\n    data.iter().map(|&(k, v)| (k, v.to_string())).collect()\n}\n",
    );

    // Generate data tables, lazy maps, and loader functions interleaved at the bottom.
    for loc in &locales {
        let data_var = loc.var_name.to_uppercase() + "_DATA";
        writeln!(buf).unwrap();
        writeln!(buf, "static {data_var}: &[(&str, &str)] = &[").unwrap();
        for (k, v) in &loc.entries {
            writeln!(buf, "    ({k:?}, {v:?}),").unwrap();
        }
        buf.push_str("];\n");
        writeln!(
            buf,
            "static {}_ONCE: OnceLock<HashMap<Key, String>> = OnceLock::new();",
            loc.var_name.to_uppercase()
        )
        .unwrap();
        // Go: `var <loc> = sync.OnceValue(func() map[Key]string { return loadLocaleData(<loc>Data) })`
        writeln!(
            buf,
            "fn {}() -> &'static HashMap<Key, String> {{\n    {}_ONCE.get_or_init(|| load_locale_data({data_var}))\n}}",
            loc.var_name,
            loc.var_name.to_uppercase(),
        )
        .unwrap();
    }

    buf
}

// `readLocalizedMessages`
fn read_localized_messages(path: &Path) -> BTreeMap<String, String> {
    let file = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to open locale file {}: {e}", path.display()));
    serde_json::from_str(&file)
        .unwrap_or_else(|e| panic!("failed to decode locale file {}: {e}", path.display()))
}

// `isLetter || isDigit` from the Go generator.
// PORT: Go uses unicode.IsLetter (L*) and unicode.IsDigit (Nd); Rust std has no
// general-category API, so we use `is_alphabetic`/`is_numeric`, which are
// slightly broader at the edges (e.g. Nl). All current message texts are pure
// ASCII, so behavior is identical.
fn is_go_letter_or_digit(r: char) -> bool {
    r.is_alphabetic() || r.is_numeric()
}

// `multipleUnderscoreRegexp.ReplaceAllString(varName, "_")` (`_+` → `_`)
fn collapse_underscores(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut prev_underscore = false;
    for c in s.chars() {
        if c == '_' {
            if prev_underscore {
                continue;
            }
            prev_underscore = true;
        } else {
            prev_underscore = false;
        }
        out.push(c);
    }
    out
}

// `convertPropertyName` — the generated var names must be byte-identical to
// Go's, so cross-crate references match.
fn convert_property_name(orig_name: &str, code: i64) -> (String, String) {
    let mut b = String::with_capacity(orig_name.len());

    for r in orig_name.chars() {
        match r {
            '*' => b.push_str("_Asterisk"),
            '/' => b.push_str("_Slash"),
            ':' => b.push_str("_Colon"),
            _ => {
                if !is_go_letter_or_digit(r) {
                    b.push('_');
                } else {
                    b.push(r);
                }
            }
        }
    }

    // get rid of all multi-underscores
    let mut var_name = collapse_underscores(&b);
    // remove any leading underscore, unless it is followed by a number.
    // (`^_+(\D)` → `$1`; after the `_+`→`_` collapse the leading run is a
    // single underscore, so this is: strip a leading `_` iff the next char is
    // a non-digit.)
    if var_name.starts_with('_')
        && var_name[1..]
            .chars()
            .next()
            .is_some_and(|c| !c.is_ascii_digit())
    {
        var_name.remove(0);
    }
    // get rid of all trailing underscores. (`_$` → ``)
    if var_name.ends_with('_') {
        var_name.pop();
    }

    let mut key = var_name.clone();
    // Go: `if len(key) > 100 { key = key[:100] }` — a byte-index truncation.
    // All message texts are ASCII today, so the cut is always on a char
    // boundary; if a non-ASCII name ever exceeds 100 bytes we snap back to the
    // boundary instead of producing invalid UTF-8 (Go would split mid-rune).
    if key.len() > 100 {
        let mut end = 100;
        while !key.is_char_boundary(end) {
            end -= 1;
        }
        key.truncate(end);
    }
    key = format!("{key}_{code}");

    // `token.IsExported` — first rune is a Unicode uppercase letter.
    // PORT: Go's unicode.IsUpper is category Lu only; char::is_uppercase also
    // includes Lt. ASCII-only in practice.
    let is_exported = var_name.chars().next().is_some_and(char::is_uppercase);
    if !is_exported {
        let mut exported = String::with_capacity(var_name.len() + 2);
        if var_name.as_bytes()[0] == b'_' {
            exported.push('X');
        } else {
            exported.push_str("X_");
        }
        exported.push_str(&var_name);
        var_name = exported;
    }

    // `!token.IsIdentifier(varName) || !token.IsExported(varName)` → fatal
    // (first char letter or '_'; rest letters/digits/'_').
    let is_identifier = {
        let mut chars = var_name.chars();
        matches!(chars.next(), Some(c) if c == '_' || c.is_alphabetic())
            && chars.all(|c| c == '_' || is_go_letter_or_digit(c))
    };
    let now_exported = var_name.chars().next().is_some_and(char::is_uppercase);
    if !is_identifier || !now_exported {
        panic!("failed to convert property name to exported identifier: {orig_name:?}");
    }

    (var_name, key)
}
