[package]
name = "tsc-jsnum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
num-bigint = { workspace = true }
tsc-stringutil = { path = "../stringutil" }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
