// Emits `kind_generated.rs` from the schema: the `Kind` enum (i16, explicit
// ordinals), `Kind*`-derived consts, `kind_string`, and `is_*_kind`
// predicates.

use std::collections::BTreeMap;

use crate::goparse::rust_name;
use crate::model::*;

/// `KindFirstAssignment` → `FIRST_ASSIGNMENT` (the emitted const name).
fn const_name(name: &str) -> String {
    let short = name.strip_prefix("Kind").unwrap_or(name);
    let mut out = String::new();
    for (i, c) in short.chars().enumerate() {
        if c.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

pub fn emit(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str(
        "// Code generated by `gen-ast` from kinds.toml; DO NOT EDIT.\n\
         // Mirrors tsc/internal/ast/kind_generated.go — ordinals match Go's\n\
         // `const ( KindX Kind = iota ... )` block exactly.\n\n",
    );
    out.push_str("/// AST node kind. `i16` repr matches Go `type Kind int16`.\n");
    out.push_str("#[repr(i16)]\n");
    out.push_str(
        "#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default, Debug)]\npub enum Kind {\n",
    );
    for (i, k) in schema.kinds.iter().enumerate() {
        let def = if i == 0 { "\n    #[default]" } else { "" };
        out.push_str(&format!("{def}\n    {k} = {i},\n"));
    }
    out.push_str("}\n\n");

    // `KindFirstX`/`KindLastX` consts. Values may reference another const
    // (`KindLastToken = KindLastKeyword`) — resolve through the const map.
    let const_map: BTreeMap<String, String> = schema
        .kind_consts
        .iter()
        .map(|c| (c.name.clone(), c.value.clone()))
        .collect();
    out.push_str("impl Kind {\n");
    for c in &schema.kind_consts {
        let value = if const_map.contains_key(&format!("Kind{}", c.value)) {
            format!("Kind::{}", const_name(&c.value))
        } else {
            format!("Kind::{}", c.value)
        };
        out.push_str(&format!(
            "    pub const {}: Kind = {};\n",
            const_name(&c.name),
            value
        ));
    }
    out.push_str(&format!(
        "    pub const COUNT: i16 = {};\n",
        schema.kinds.len()
    ));
    out.push_str("}\n\n");

    // `Kind.String()` — Go stringer returns the full `KindX` name.
    out.push_str("impl Kind {\n");
    out.push_str("    /// Go `Kind.String()` — the full `KindX` name.\n");
    out.push_str("    pub fn kind_string(&self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for k in &schema.kinds {
        out.push_str(&format!("            Kind::{k} => \"Kind{k}\",\n"));
    }
    out.push_str("        }\n    }\n");

    // `stringToKind` — Go's reverse lookup in the stringer-adjacent helpers.
    out.push_str("\n    /// Go `stringToKind`.\n");
    out.push_str("    pub fn from_kind_string(s: &str) -> Option<Kind> {\n");
    out.push_str("        Some(match s {\n");
    for k in &schema.kinds {
        out.push_str(&format!("            \"Kind{k}\" => Kind::{k},\n"));
    }
    out.push_str("            _ => return None,\n");
    out.push_str("        })\n    }\n}\n\n");

    // `IsXKind` predicates → `impl Kind` methods.
    out.push_str("impl Kind {\n");
    for p in &schema.kind_preds {
        let method = pred_method(&p.name);
        emit_pred_body(&mut out, &method, p, "        ");
    }
    out.push_str("}\n\n");

    // `XSyntaxKind` aliases — emitted as marker fns so hand code can name the
    // sets (Go uses them only as documentation).
    out.push_str("// `type XSyntaxKind = Kind` aliases — the kind sets they\n");
    out.push_str("// denote, for documentation and bootstrap completeness.\n");
    out.push_str("impl Kind {\n");
    for a in &schema.kind_aliases {
        let method = rust_name(&format!("Is{}", a.name));
        let method = method.strip_suffix("_syntax_kind").unwrap_or(&method);
        out.push_str(&format!(
            "    /// `{}` kinds.\n    #[allow(dead_code)]\n    pub fn is_{}(&self) -> bool {{\n",
            a.name, method
        ));
        if a.kinds.is_empty() {
            out.push_str("        false\n");
        } else {
            let arms: Vec<String> = a.kinds.iter().map(|k| format!("Kind::{k}")).collect();
            out.push_str(&format!("        matches!(self, {})\n", arms.join(" | ")));
        }
        out.push_str("    }\n");
    }
    out.push_str("}\n");
    out
}

/// `IsTokenKind` → `is_token_kind`.
fn pred_method(name: &str) -> String {
    rust_name(name)
}

fn emit_pred_body(out: &mut String, method: &str, p: &KindPred, indent: &str) {
    out.push_str(&format!("{indent}/// `{name}`.\n", name = p.name));
    out.push_str(&format!("{indent}pub fn {method}(&self) -> bool {{\n"));
    if let Some(d) = &p.delegate {
        out.push_str(&format!("{indent}    self.{}()\n", pred_method(d)));
    } else if let Some([lo, hi]) = &p.range {
        out.push_str(&format!(
            "{indent}    *self >= Kind::{} && *self <= Kind::{}\n",
            const_name(lo),
            const_name(hi)
        ));
    } else if !p.kinds.is_empty() {
        let arms: Vec<String> = p.kinds.iter().map(|k| format!("Kind::{k}")).collect();
        out.push_str(&format!(
            "{indent}    matches!(self, {})\n",
            arms.join(" | ")
        ));
    } else {
        out.push_str(&format!(
            "{indent}    false // TODO: {name} not emitted\n",
            name = p.name
        ));
    }
    out.push_str(&format!("{indent}}}\n"));
}
