[package]
name = "tsc-ast"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tsc-collections = { path = "../collections" }
tsc-core = { path = "../core" }
tsc-debug = { path = "../debug" }
tsc-diagnostics = { path = "../diagnostics" }
tsc-locale = { path = "../locale" }
tsc-spanmap = { path = "../spanmap" }
tsc-stringutil = { path = "../stringutil" }
tsc-tspath = { path = "../tspath" }
rustc-hash = { workspace = true }

[lints]
workspace = true
