[package]
name = "tsc-ast"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tsc-core = { path = "../core" }
tsc-collections = { path = "../collections" }
tsc-diagnostics = { path = "../diagnostics" }
tsc-stringutil = { path = "../stringutil" }
tsc-tspath = { path = "../tspath" }

[lints]
workspace = true
